// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sundae.proto

package sundae

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SundaeDataMessage struct {
	// @inject_tag: structs:"regen_enabled,indirect" csv:"regen_enabled"
	RegenEnabled *uint32 `protobuf:"varint,1,opt,name=regen_enabled,json=regenEnabled" json:"regen_enabled,omitempty" structs:"regen_enabled,indirect" csv:"regen_enabled"`
	// @inject_tag: structs:"regen_command,indirect" csv:"regen_command"
	RegenCommand *uint32 `protobuf:"varint,2,opt,name=regen_command,json=regenCommand" json:"regen_command,omitempty" structs:"regen_command,indirect" csv:"regen_command"`
	// @inject_tag: structs:"battery_power,indirect" csv:"battery_power"
	BatteryPower *uint32 `protobuf:"varint,3,opt,name=battery_power,json=batteryPower" json:"battery_power,omitempty" structs:"battery_power,indirect" csv:"battery_power"`
	// @inject_tag: structs:"array_power,indirect" csv:"array_power"
	ArrayPower *float32 `protobuf:"fixed32,4,opt,name=array_power,json=arrayPower" json:"array_power,omitempty" structs:"array_power,indirect" csv:"array_power"`
	// @inject_tag: structs:"reverse_on,indirect" csv:"reverse_on"
	ReverseOn *uint32 `protobuf:"varint,5,opt,name=reverse_on,json=reverseOn" json:"reverse_on,omitempty" structs:"reverse_on,indirect" csv:"reverse_on"`
	// @inject_tag: structs:"low_volt_power,indirect" csv:"low_volt_power"
	LowVoltPower *float32 `protobuf:"fixed32,6,opt,name=low_volt_power,json=lowVoltPower" json:"low_volt_power,omitempty" structs:"low_volt_power,indirect" csv:"low_volt_power"`
	// @inject_tag: structs:"cell_read_error,indirect" csv:"cell_read_error"
	CellReadError *int32 `protobuf:"varint,7,opt,name=cell_read_error,json=cellReadError" json:"cell_read_error,omitempty" structs:"cell_read_error,indirect" csv:"cell_read_error"`
	// @inject_tag: structs:"cell_bleed,indirect" csv:"cell_bleed"
	CellBleed *uint32 `protobuf:"varint,8,opt,name=cell_bleed,json=cellBleed" json:"cell_bleed,omitempty" structs:"cell_bleed,indirect" csv:"cell_bleed"`
	// @inject_tag: structs:"cruise_speed,indirect" csv:"cruise_speed"
	CruiseSpeed *float32 `protobuf:"fixed32,9,opt,name=cruise_speed,json=cruiseSpeed" json:"cruise_speed,omitempty" structs:"cruise_speed,indirect" csv:"cruise_speed"`
	// @inject_tag: structs:"hazard_lights_on,indirect" csv:"hazard_lights_on"
	HazardLightsOn *int32 `protobuf:"varint,10,opt,name=hazard_lights_on,json=hazardLightsOn" json:"hazard_lights_on,omitempty" structs:"hazard_lights_on,indirect" csv:"hazard_lights_on"`
	// @inject_tag: structs:"battery_voltage,indirect" csv:"battery_voltage"
	BatteryVoltage *float32 `protobuf:"fixed32,11,opt,name=battery_voltage,json=batteryVoltage" json:"battery_voltage,omitempty" structs:"battery_voltage,indirect" csv:"battery_voltage"`
	// @inject_tag: structs:"ltc6804_badpec,indirect" csv:"ltc6804_badpec"
	Ltc6804Badpec *uint32 `protobuf:"varint,12,opt,name=ltc6804_badpec,json=ltc6804Badpec" json:"ltc6804_badpec,omitempty" structs:"ltc6804_badpec,indirect" csv:"ltc6804_badpec"`
	// @inject_tag: structs:"bms_state,indirect" csv:"bms_state"
	BmsState *uint32 `protobuf:"varint,13,opt,name=bms_state,json=bmsState" json:"bms_state,omitempty" structs:"bms_state,indirect" csv:"bms_state"`
	// @inject_tag: structs:"charge_enabled,indirect" csv:"charge_enabled"
	ChargeEnabled *int32 `protobuf:"varint,14,opt,name=charge_enabled,json=chargeEnabled" json:"charge_enabled,omitempty" structs:"charge_enabled,indirect" csv:"charge_enabled"`
	// @inject_tag: structs:"discharge_enabled,indirect" csv:"discharge_enabled"
	DischargeEnabled *int32 `protobuf:"varint,15,opt,name=discharge_enabled,json=dischargeEnabled" json:"discharge_enabled,omitempty" structs:"discharge_enabled,indirect" csv:"discharge_enabled"`
	// @inject_tag: structs:"highside_contactor_on,indirect" csv:"highside_contactor_on"
	HighsideContactorOn *int32 `protobuf:"varint,16,opt,name=highside_contactor_on,json=highsideContactorOn" json:"highside_contactor_on,omitempty" structs:"highside_contactor_on,indirect" csv:"highside_contactor_on"`
	// @inject_tag: structs:"lowside_contactor_on,indirect" csv:"lowside_contactor_on"
	LowsideContactorOn *int32 `protobuf:"varint,17,opt,name=lowside_contactor_on,json=lowsideContactorOn" json:"lowside_contactor_on,omitempty" structs:"lowside_contactor_on,indirect" csv:"lowside_contactor_on"`
	// @inject_tag: structs:"precharge_on,indirect" csv:"precharge_on"
	PrechargeOn *int32 `protobuf:"varint,18,opt,name=precharge_on,json=prechargeOn" json:"precharge_on,omitempty" structs:"precharge_on,indirect" csv:"precharge_on"`
	// @inject_tag: structs:"low_volt_bus_on,indirect" csv:"low_volt_bus_on"
	LowVoltBusOn *int32 `protobuf:"varint,19,opt,name=low_volt_bus_on,json=lowVoltBusOn" json:"low_volt_bus_on,omitempty" structs:"low_volt_bus_on,indirect" csv:"low_volt_bus_on"`
	// @inject_tag: structs:"battery_temp_1,indirect" csv:"battery_temp_1"
	BatteryTemp_1 *float32 `protobuf:"fixed32,20,opt,name=battery_temp_1,json=batteryTemp1" json:"battery_temp_1,omitempty" structs:"battery_temp_1,indirect" csv:"battery_temp_1"`
	// @inject_tag: structs:"battery_temp_2,indirect" csv:"battery_temp_2"
	BatteryTemp_2 *float32 `protobuf:"fixed32,21,opt,name=battery_temp_2,json=batteryTemp2" json:"battery_temp_2,omitempty" structs:"battery_temp_2,indirect" csv:"battery_temp_2"`
	// @inject_tag: structs:"battery_temp_3,indirect" csv:"battery_temp_3"
	BatteryTemp_3 *float32 `protobuf:"fixed32,22,opt,name=battery_temp_3,json=batteryTemp3" json:"battery_temp_3,omitempty" structs:"battery_temp_3,indirect" csv:"battery_temp_3"`
	// @inject_tag: structs:"battery_temp_4,indirect" csv:"battery_temp_4"
	BatteryTemp_4 *float32 `protobuf:"fixed32,23,opt,name=battery_temp_4,json=batteryTemp4" json:"battery_temp_4,omitempty" structs:"battery_temp_4,indirect" csv:"battery_temp_4"`
	// @inject_tag: structs:"battery_temp_5,indirect" csv:"battery_temp_5"
	BatteryTemp_5 *float32 `protobuf:"fixed32,24,opt,name=battery_temp_5,json=batteryTemp5" json:"battery_temp_5,omitempty" structs:"battery_temp_5,indirect" csv:"battery_temp_5"`
	// @inject_tag: structs:"battery_temp_6,indirect" csv:"battery_temp_6"
	BatteryTemp_6 *float32 `protobuf:"fixed32,25,opt,name=battery_temp_6,json=batteryTemp6" json:"battery_temp_6,omitempty" structs:"battery_temp_6,indirect" csv:"battery_temp_6"`
	// @inject_tag: structs:"bms_precharge_battery_adc,indirect" csv:"bms_precharge_battery_adc"
	BmsPrechargeBatteryAdc *float32 `protobuf:"fixed32,26,opt,name=bms_precharge_battery_adc,json=bmsPrechargeBatteryAdc" json:"bms_precharge_battery_adc,omitempty" structs:"bms_precharge_battery_adc,indirect" csv:"bms_precharge_battery_adc"`
	// @inject_tag: structs:"bms_precharge_car_adc,indirect" csv:"bms_precharge_car_adc"
	BmsPrechargeCarAdc *float32 `protobuf:"fixed32,27,opt,name=bms_precharge_car_adc,json=bmsPrechargeCarAdc" json:"bms_precharge_car_adc,omitempty" structs:"bms_precharge_car_adc,indirect" csv:"bms_precharge_car_adc"`
	// @inject_tag: structs:"low_volt_output_current,indirect" csv:"low_volt_output_current"
	LowVoltOutputCurrent *float32 `protobuf:"fixed32,29,opt,name=low_volt_output_current,json=lowVoltOutputCurrent" json:"low_volt_output_current,omitempty" structs:"low_volt_output_current,indirect" csv:"low_volt_output_current"`
	// @inject_tag: structs:"array_current,indirect" csv:"array_current"
	ArrayCurrent *float32 `protobuf:"fixed32,30,opt,name=array_current,json=arrayCurrent" json:"array_current,omitempty" structs:"array_current,indirect" csv:"array_current"`
	// @inject_tag: structs:"battery_current,indirect" csv:"battery_current"
	BatteryCurrent *float32 `protobuf:"fixed32,31,opt,name=battery_current,json=batteryCurrent" json:"battery_current,omitempty" structs:"battery_current,indirect" csv:"battery_current"`
	// @inject_tag: structs:"left_motor_controller_power,indirect" csv:"left_motor_controller_power"
	LeftMotorControllerPower *float32 `protobuf:"fixed32,32,opt,name=left_motor_controller_power,json=leftMotorControllerPower" json:"left_motor_controller_power,omitempty" structs:"left_motor_controller_power,indirect" csv:"left_motor_controller_power"`
	// @inject_tag: structs:"right_motor_controller_power,indirect" csv:"right_motor_controller_power"
	RightMotorControllerPower *float32 `protobuf:"fixed32,33,opt,name=right_motor_controller_power,json=rightMotorControllerPower" json:"right_motor_controller_power,omitempty" structs:"right_motor_controller_power,indirect" csv:"right_motor_controller_power"`
	// @inject_tag: structs:"amp_hours,indirect" csv:"amp_hours"
	AmpHours *float32 `protobuf:"fixed32,34,opt,name=amp_hours,json=ampHours" json:"amp_hours,omitempty" structs:"amp_hours,indirect" csv:"amp_hours"`
	// @inject_tag: structs:"head_lights_on,indirect" csv:"head_lights_on"
	HeadLightsOn *int32 `protobuf:"varint,35,opt,name=head_lights_on,json=headLightsOn" json:"head_lights_on,omitempty" structs:"head_lights_on,indirect" csv:"head_lights_on"`
	// @inject_tag: structs:"brake_lights_on,indirect" csv:"brake_lights_on"
	BrakeLightsOn *int32 `protobuf:"varint,36,opt,name=brake_lights_on,json=brakeLightsOn" json:"brake_lights_on,omitempty" structs:"brake_lights_on,indirect" csv:"brake_lights_on"`
	// @inject_tag: structs:"right_blinker_on,indirect" csv:"right_blinker_on"
	RightBlinkerOn *int32 `protobuf:"varint,37,opt,name=right_blinker_on,json=rightBlinkerOn" json:"right_blinker_on,omitempty" structs:"right_blinker_on,indirect" csv:"right_blinker_on"`
	// @inject_tag: structs:"left_blinker_on,indirect" csv:"left_blinker_on"
	LeftBlinkerOn *int32 `protobuf:"varint,38,opt,name=left_blinker_on,json=leftBlinkerOn" json:"left_blinker_on,omitempty" structs:"left_blinker_on,indirect" csv:"left_blinker_on"`
	// @inject_tag: structs:"brake_pressed,indirect" csv:"brake_pressed"
	BrakePressed *int32 `protobuf:"varint,39,opt,name=brake_pressed,json=brakePressed" json:"brake_pressed,omitempty" structs:"brake_pressed,indirect" csv:"brake_pressed"`
	// @inject_tag: structs:"throttle_pressed,indirect" csv:"throttle_pressed"
	ThrottlePressed *int32 `protobuf:"varint,40,opt,name=throttle_pressed,json=throttlePressed" json:"throttle_pressed,omitempty" structs:"throttle_pressed,indirect" csv:"throttle_pressed"`
	// @inject_tag: structs:"drive_mode,indirect" csv:"drive_mode"
	DriveMode *uint32 `protobuf:"varint,41,opt,name=drive_mode,json=driveMode" json:"drive_mode,omitempty" structs:"drive_mode,indirect" csv:"drive_mode"`
	// @inject_tag: structs:"motor_controller_enabled,indirect" csv:"motor_controller_enabled"
	MotorControllerEnabled *int32 `protobuf:"varint,42,opt,name=motor_controller_enabled,json=motorControllerEnabled" json:"motor_controller_enabled,omitempty" structs:"motor_controller_enabled,indirect" csv:"motor_controller_enabled"`
	// @inject_tag: structs:"motor_controller_speed,indirect" csv:"motor_controller_speed"
	MotorControllerSpeed *float32 `protobuf:"fixed32,43,opt,name=motor_controller_speed,json=motorControllerSpeed" json:"motor_controller_speed,omitempty" structs:"motor_controller_speed,indirect" csv:"motor_controller_speed"`
	// @inject_tag: structs:"motor_controller_rpm,indirect" csv:"motor_controller_rpm"
	MotorControllerRpm *float32 `protobuf:"fixed32,44,opt,name=motor_controller_rpm,json=motorControllerRpm" json:"motor_controller_rpm,omitempty" structs:"motor_controller_rpm,indirect" csv:"motor_controller_rpm"`
	// @inject_tag: structs:"avg_odometer,indirect" csv:"avg_odometer"
	AvgOdometer *float32 `protobuf:"fixed32,45,opt,name=avg_odometer,json=avgOdometer" json:"avg_odometer,omitempty" structs:"avg_odometer,indirect" csv:"avg_odometer"`
	// @inject_tag: structs:"left_motor_temp,indirect" csv:"left_motor_temp"
	LeftMotorTemp *float32 `protobuf:"fixed32,46,opt,name=left_motor_temp,json=leftMotorTemp" json:"left_motor_temp,omitempty" structs:"left_motor_temp,indirect" csv:"left_motor_temp"`
	// @inject_tag: structs:"right_motor_temp,indirect" csv:"right_motor_temp"
	RightMotorTemp *float32 `protobuf:"fixed32,47,opt,name=right_motor_temp,json=rightMotorTemp" json:"right_motor_temp,omitempty" structs:"right_motor_temp,indirect" csv:"right_motor_temp"`
	// @inject_tag: structs:"left_motor_controller_temp,indirect" csv:"left_motor_controller_temp"
	LeftMotorControllerTemp *float32 `protobuf:"fixed32,48,opt,name=left_motor_controller_temp,json=leftMotorControllerTemp" json:"left_motor_controller_temp,omitempty" structs:"left_motor_controller_temp,indirect" csv:"left_motor_controller_temp"`
	// @inject_tag: structs:"right_motor_controller_temp,indirect" csv:"right_motor_controller_temp"
	RightMotorControllerTemp *float32 `protobuf:"fixed32,49,opt,name=right_motor_controller_temp,json=rightMotorControllerTemp" json:"right_motor_controller_temp,omitempty" structs:"right_motor_controller_temp,indirect" csv:"right_motor_controller_temp"`
	// @inject_tag: structs:"left_motor_controller_alive,indirect" csv:"left_motor_controller_alive"
	LeftMotorControllerAlive *float32 `protobuf:"fixed32,50,opt,name=left_motor_controller_alive,json=leftMotorControllerAlive" json:"left_motor_controller_alive,omitempty" structs:"left_motor_controller_alive,indirect" csv:"left_motor_controller_alive"`
	// @inject_tag: structs:"right_motor_controller_alive,indirect" csv:"right_motor_controller_alive"
	RightMotorControllerAlive *float32 `protobuf:"fixed32,51,opt,name=right_motor_controller_alive,json=rightMotorControllerAlive" json:"right_motor_controller_alive,omitempty" structs:"right_motor_controller_alive,indirect" csv:"right_motor_controller_alive"`
	// @inject_tag: structs:"left_motor_controller_current,indirect" csv:"left_motor_controller_current"
	LeftMotorControllerCurrent *float32 `protobuf:"fixed32,52,opt,name=left_motor_controller_current,json=leftMotorControllerCurrent" json:"left_motor_controller_current,omitempty" structs:"left_motor_controller_current,indirect" csv:"left_motor_controller_current"`
	// @inject_tag: structs:"right_motor_controller_current,indirect" csv:"right_motor_controller_current"
	RightMotorControllerCurrent *float32 `protobuf:"fixed32,53,opt,name=right_motor_controller_current,json=rightMotorControllerCurrent" json:"right_motor_controller_current,omitempty" structs:"right_motor_controller_current,indirect" csv:"right_motor_controller_current"`
	// @inject_tag: structs:"motor_controller_current_diff,indirect" csv:"motor_controller_current_diff"
	MotorControllerCurrentDiff *float32 `protobuf:"fixed32,54,opt,name=motor_controller_current_diff,json=motorControllerCurrentDiff" json:"motor_controller_current_diff,omitempty" structs:"motor_controller_current_diff,indirect" csv:"motor_controller_current_diff"`
	// @inject_tag: structs:"left_motor_controller_error,indirect" csv:"left_motor_controller_error"
	LeftMotorControllerError *uint32 `protobuf:"varint,55,opt,name=left_motor_controller_error,json=leftMotorControllerError" json:"left_motor_controller_error,omitempty" structs:"left_motor_controller_error,indirect" csv:"left_motor_controller_error"`
	// @inject_tag: structs:"right_motor_controller_error,indirect" csv:"right_motor_controller_error"
	RightMotorControllerError *uint32 `protobuf:"varint,56,opt,name=right_motor_controller_error,json=rightMotorControllerError" json:"right_motor_controller_error,omitempty" structs:"right_motor_controller_error,indirect" csv:"right_motor_controller_error"`
	// @inject_tag: structs:"left_motor_controller_limit,indirect" csv:"left_motor_controller_limit"
	LeftMotorControllerLimit *uint32 `protobuf:"varint,57,opt,name=left_motor_controller_limit,json=leftMotorControllerLimit" json:"left_motor_controller_limit,omitempty" structs:"left_motor_controller_limit,indirect" csv:"left_motor_controller_limit"`
	// @inject_tag: structs:"right_motor_controller_limit,indirect" csv:"right_motor_controller_limit"
	RightMotorControllerLimit *uint32 `protobuf:"varint,58,opt,name=right_motor_controller_limit,json=rightMotorControllerLimit" json:"right_motor_controller_limit,omitempty" structs:"right_motor_controller_limit,indirect" csv:"right_motor_controller_limit"`
	// @inject_tag: structs:"left_motor_controller_rx_error_count,indirect" csv:"left_motor_controller_rx_error_count"
	LeftMotorControllerRxErrorCount *uint32 `protobuf:"varint,59,opt,name=left_motor_controller_rx_error_count,json=leftMotorControllerRxErrorCount" json:"left_motor_controller_rx_error_count,omitempty" structs:"left_motor_controller_rx_error_count,indirect" csv:"left_motor_controller_rx_error_count"`
	// @inject_tag: structs:"right_motor_controller_rx_error_count,indirect" csv:"right_motor_controller_rx_error_count"
	RightMotorControllerRxErrorCount *uint32 `protobuf:"varint,60,opt,name=right_motor_controller_rx_error_count,json=rightMotorControllerRxErrorCount" json:"right_motor_controller_rx_error_count,omitempty" structs:"right_motor_controller_rx_error_count,indirect" csv:"right_motor_controller_rx_error_count"`
	// @inject_tag: structs:"left_motor_controller_tx_error_count,indirect" csv:"left_motor_controller_tx_error_count"
	LeftMotorControllerTxErrorCount *uint32 `protobuf:"varint,61,opt,name=left_motor_controller_tx_error_count,json=leftMotorControllerTxErrorCount" json:"left_motor_controller_tx_error_count,omitempty" structs:"left_motor_controller_tx_error_count,indirect" csv:"left_motor_controller_tx_error_count"`
	// @inject_tag: structs:"right_motor_controller_tx_error_count,indirect" csv:"right_motor_controller_tx_error_count"
	RightMotorControllerTxErrorCount *uint32 `protobuf:"varint,62,opt,name=right_motor_controller_tx_error_count,json=rightMotorControllerTxErrorCount" json:"right_motor_controller_tx_error_count,omitempty" structs:"right_motor_controller_tx_error_count,indirect" csv:"right_motor_controller_tx_error_count"`
	// @inject_tag: structs:"left_motor_controller_bus_voltage,indirect" csv:"left_motor_controller_bus_voltage"
	LeftMotorControllerBusVoltage *float32 `protobuf:"fixed32,63,opt,name=left_motor_controller_bus_voltage,json=leftMotorControllerBusVoltage" json:"left_motor_controller_bus_voltage,omitempty" structs:"left_motor_controller_bus_voltage,indirect" csv:"left_motor_controller_bus_voltage"`
	// @inject_tag: structs:"right_motor_controller_bus_voltage,indirect" csv:"right_motor_controller_bus_voltage"
	RightMotorControllerBusVoltage *float32 `protobuf:"fixed32,64,opt,name=right_motor_controller_bus_voltage,json=rightMotorControllerBusVoltage" json:"right_motor_controller_bus_voltage,omitempty" structs:"right_motor_controller_bus_voltage,indirect" csv:"right_motor_controller_bus_voltage"`
	// @inject_tag: structs:"left_motor_controller_15v_voltage,indirect" csv:"left_motor_controller_15v_voltage"
	LeftMotorController_15VVoltage *float32 `protobuf:"fixed32,65,opt,name=left_motor_controller_15v_voltage,json=leftMotorController15vVoltage" json:"left_motor_controller_15v_voltage,omitempty" structs:"left_motor_controller_15v_voltage,indirect" csv:"left_motor_controller_15v_voltage"`
	// @inject_tag: structs:"right_motor_controller_15v_voltage,indirect" csv:"right_motor_controller_15v_voltage"
	RightMotorController_15VVoltage *float32 `protobuf:"fixed32,66,opt,name=right_motor_controller_15v_voltage,json=rightMotorController15vVoltage" json:"right_motor_controller_15v_voltage,omitempty" structs:"right_motor_controller_15v_voltage,indirect" csv:"right_motor_controller_15v_voltage"`
	// @inject_tag: structs:"left_motor_controller_3v3_voltage,indirect" csv:"left_motor_controller_3v3_voltage"
	LeftMotorController_3V3Voltage *float32 `protobuf:"fixed32,67,opt,name=left_motor_controller_3v3_voltage,json=leftMotorController3v3Voltage" json:"left_motor_controller_3v3_voltage,omitempty" structs:"left_motor_controller_3v3_voltage,indirect" csv:"left_motor_controller_3v3_voltage"`
	// @inject_tag: structs:"right_motor_controller_3v3_voltage,indirect" csv:"right_motor_controller_3v3_voltage"
	RightMotorController_3V3Voltage *float32 `protobuf:"fixed32,68,opt,name=right_motor_controller_3v3_voltage,json=rightMotorController3v3Voltage" json:"right_motor_controller_3v3_voltage,omitempty" structs:"right_motor_controller_3v3_voltage,indirect" csv:"right_motor_controller_3v3_voltage"`
	// @inject_tag: structs:"left_motor_controller_1v9_voltage,indirect" csv:"left_motor_controller_1v9_voltage"
	LeftMotorController_1V9Voltage *float32 `protobuf:"fixed32,69,opt,name=left_motor_controller_1v9_voltage,json=leftMotorController1v9Voltage" json:"left_motor_controller_1v9_voltage,omitempty" structs:"left_motor_controller_1v9_voltage,indirect" csv:"left_motor_controller_1v9_voltage"`
	// @inject_tag: structs:"right_motor_controller_1v9_voltage,indirect" csv:"right_motor_controller_1v9_voltage"
	RightMotorController_1V9Voltage *float32 `protobuf:"fixed32,70,opt,name=right_motor_controller_1v9_voltage,json=rightMotorController1v9Voltage" json:"right_motor_controller_1v9_voltage,omitempty" structs:"right_motor_controller_1v9_voltage,indirect" csv:"right_motor_controller_1v9_voltage"`
	// @inject_tag: structs:"left_motor_controller_dsp_temp,indirect" csv:"left_motor_controller_dsp_temp"
	LeftMotorControllerDspTemp *float32 `protobuf:"fixed32,71,opt,name=left_motor_controller_dsp_temp,json=leftMotorControllerDspTemp" json:"left_motor_controller_dsp_temp,omitempty" structs:"left_motor_controller_dsp_temp,indirect" csv:"left_motor_controller_dsp_temp"`
	// @inject_tag: structs:"right_motor_controller_dsp_temp,indirect" csv:"right_motor_controller_dsp_temp"
	RightMotorControllerDspTemp *float32 `protobuf:"fixed32,72,opt,name=right_motor_controller_dsp_temp,json=rightMotorControllerDspTemp" json:"right_motor_controller_dsp_temp,omitempty" structs:"right_motor_controller_dsp_temp,indirect" csv:"right_motor_controller_dsp_temp"`
	// @inject_tag: structs:"left_motor_controller_phase_current,indirect" csv:"left_motor_controller_phase_current"
	LeftMotorControllerPhaseCurrent *float32 `protobuf:"fixed32,73,opt,name=left_motor_controller_phase_current,json=leftMotorControllerPhaseCurrent" json:"left_motor_controller_phase_current,omitempty" structs:"left_motor_controller_phase_current,indirect" csv:"left_motor_controller_phase_current"`
	// @inject_tag: structs:"right_motor_controller_phase_current,indirect" csv:"right_motor_controller_phase_current"
	RightMotorControllerPhaseCurrent *float32 `protobuf:"fixed32,74,opt,name=right_motor_controller_phase_current,json=rightMotorControllerPhaseCurrent" json:"right_motor_controller_phase_current,omitempty" structs:"right_motor_controller_phase_current,indirect" csv:"right_motor_controller_phase_current"`
	// @inject_tag: structs:"left_motor_rpm_command,indirect" csv:"left_motor_rpm_command"
	LeftMotorRpmCommand *float32 `protobuf:"fixed32,75,opt,name=left_motor_rpm_command,json=leftMotorRpmCommand" json:"left_motor_rpm_command,omitempty" structs:"left_motor_rpm_command,indirect" csv:"left_motor_rpm_command"`
	// @inject_tag: structs:"right_motor_rpm_command,indirect" csv:"right_motor_rpm_command"
	RightMotorRpmCommand *float32 `protobuf:"fixed32,76,opt,name=right_motor_rpm_command,json=rightMotorRpmCommand" json:"right_motor_rpm_command,omitempty" structs:"right_motor_rpm_command,indirect" csv:"right_motor_rpm_command"`
	// @inject_tag: structs:"left_motor_current_command,indirect" csv:"left_motor_current_command"
	LeftMotorCurrentCommand *float32 `protobuf:"fixed32,77,opt,name=left_motor_current_command,json=leftMotorCurrentCommand" json:"left_motor_current_command,omitempty" structs:"left_motor_current_command,indirect" csv:"left_motor_current_command"`
	// @inject_tag: structs:"right_motor_current_command,indirect" csv:"right_motor_current_command"
	RightMotorCurrentCommand *float32 `protobuf:"fixed32,78,opt,name=right_motor_current_command,json=rightMotorCurrentCommand" json:"right_motor_current_command,omitempty" structs:"right_motor_current_command,indirect" csv:"right_motor_current_command"`
	// @inject_tag: structs:"gps_time,indirect" csv:"gps_time"
	GpsTime *int64 `protobuf:"varint,80,opt,name=gps_time,json=gpsTime" json:"gps_time,omitempty" structs:"gps_time,indirect" csv:"gps_time"`
	// @inject_tag: structs:"gps_latitude,indirect" csv:"gps_latitude"
	GpsLatitude *float32 `protobuf:"fixed32,81,opt,name=gps_latitude,json=gpsLatitude" json:"gps_latitude,omitempty" structs:"gps_latitude,indirect" csv:"gps_latitude"`
	// @inject_tag: structs:"gps_longitude,indirect" csv:"gps_longitude"
	GpsLongitude *float32 `protobuf:"fixed32,82,opt,name=gps_longitude,json=gpsLongitude" json:"gps_longitude,omitempty" structs:"gps_longitude,indirect" csv:"gps_longitude"`
	// @inject_tag: structs:"gps_speed,indirect" csv:"gps_speed"
	GpsSpeed *float32 `protobuf:"fixed32,83,opt,name=gps_speed,json=gpsSpeed" json:"gps_speed,omitempty" structs:"gps_speed,indirect" csv:"gps_speed"`
	// @inject_tag: structs:"gps_altitude,indirect" csv:"gps_altitude"
	GpsAltitude *float32 `protobuf:"fixed32,84,opt,name=gps_altitude,json=gpsAltitude" json:"gps_altitude,omitempty" structs:"gps_altitude,indirect" csv:"gps_altitude"`
	// @inject_tag: structs:"gps_bearing,indirect" csv:"gps_bearing"
	GpsBearing *float32 `protobuf:"fixed32,85,opt,name=gps_bearing,json=gpsBearing" json:"gps_bearing,omitempty" structs:"gps_bearing,indirect" csv:"gps_bearing"`
	// @inject_tag: structs:"led_state,indirect" csv:"led_state"
	LedState *int32 `protobuf:"varint,86,opt,name=led_state,json=ledState" json:"led_state,omitempty" structs:"led_state,indirect" csv:"led_state"`
	// @inject_tag: structs:"mppt_array_power,indirect" csv:"mppt_array_power"
	MpptArrayPower *float32 `protobuf:"fixed32,87,opt,name=mppt_array_power,json=mpptArrayPower" json:"mppt_array_power,omitempty" structs:"mppt_array_power,indirect" csv:"mppt_array_power"`
	// @inject_tag: structs:"mppt_A0_volt_in,indirect" csv:"mppt_A0_volt_in"
	Mppt_A0VoltIn *float32 `protobuf:"fixed32,88,opt,name=mppt_A0_volt_in,json=mpptA0VoltIn" json:"mppt_A0_volt_in,omitempty" structs:"mppt_A0_volt_in,indirect" csv:"mppt_A0_volt_in"`
	// @inject_tag: structs:"mppt_A0_volt_out,indirect" csv:"mppt_A0_volt_out"
	Mppt_A0VoltOut *float32 `protobuf:"fixed32,89,opt,name=mppt_A0_volt_out,json=mpptA0VoltOut" json:"mppt_A0_volt_out,omitempty" structs:"mppt_A0_volt_out,indirect" csv:"mppt_A0_volt_out"`
	// @inject_tag: structs:"mppt_A0_current,indirect" csv:"mppt_A0_current"
	Mppt_A0Current *float32 `protobuf:"fixed32,90,opt,name=mppt_A0_current,json=mpptA0Current" json:"mppt_A0_current,omitempty" structs:"mppt_A0_current,indirect" csv:"mppt_A0_current"`
	// @inject_tag: structs:"mppt_A0_temp,indirect" csv:"mppt_A0_temp"
	Mppt_A0Temp *float32 `protobuf:"fixed32,91,opt,name=mppt_A0_temp,json=mpptA0Temp" json:"mppt_A0_temp,omitempty" structs:"mppt_A0_temp,indirect" csv:"mppt_A0_temp"`
	// @inject_tag: structs:"mppt_A1_volt_in,indirect" csv:"mppt_A1_volt_in"
	Mppt_A1VoltIn *float32 `protobuf:"fixed32,92,opt,name=mppt_A1_volt_in,json=mpptA1VoltIn" json:"mppt_A1_volt_in,omitempty" structs:"mppt_A1_volt_in,indirect" csv:"mppt_A1_volt_in"`
	// @inject_tag: structs:"mppt_A1_volt_out,indirect" csv:"mppt_A1_volt_out"
	Mppt_A1VoltOut *float32 `protobuf:"fixed32,93,opt,name=mppt_A1_volt_out,json=mpptA1VoltOut" json:"mppt_A1_volt_out,omitempty" structs:"mppt_A1_volt_out,indirect" csv:"mppt_A1_volt_out"`
	// @inject_tag: structs:"mppt_A1_current,indirect" csv:"mppt_A1_current"
	Mppt_A1Current *float32 `protobuf:"fixed32,94,opt,name=mppt_A1_current,json=mpptA1Current" json:"mppt_A1_current,omitempty" structs:"mppt_A1_current,indirect" csv:"mppt_A1_current"`
	// @inject_tag: structs:"mppt_A1_temp,indirect" csv:"mppt_A1_temp"
	Mppt_A1Temp *float32 `protobuf:"fixed32,95,opt,name=mppt_A1_temp,json=mpptA1Temp" json:"mppt_A1_temp,omitempty" structs:"mppt_A1_temp,indirect" csv:"mppt_A1_temp"`
	// @inject_tag: structs:"mppt_B0_volt_in,indirect" csv:"mppt_B0_volt_in"
	Mppt_B0VoltIn *float32 `protobuf:"fixed32,96,opt,name=mppt_B0_volt_in,json=mpptB0VoltIn" json:"mppt_B0_volt_in,omitempty" structs:"mppt_B0_volt_in,indirect" csv:"mppt_B0_volt_in"`
	// @inject_tag: structs:"mppt_B0_volt_out,indirect" csv:"mppt_B0_volt_out"
	Mppt_B0VoltOut *float32 `protobuf:"fixed32,97,opt,name=mppt_B0_volt_out,json=mpptB0VoltOut" json:"mppt_B0_volt_out,omitempty" structs:"mppt_B0_volt_out,indirect" csv:"mppt_B0_volt_out"`
	// @inject_tag: structs:"mppt_B0_current,indirect" csv:"mppt_B0_current"
	Mppt_B0Current *float32 `protobuf:"fixed32,98,opt,name=mppt_B0_current,json=mpptB0Current" json:"mppt_B0_current,omitempty" structs:"mppt_B0_current,indirect" csv:"mppt_B0_current"`
	// @inject_tag: structs:"mppt_B0_temp,indirect" csv:"mppt_B0_temp"
	Mppt_B0Temp *float32 `protobuf:"fixed32,99,opt,name=mppt_B0_temp,json=mpptB0Temp" json:"mppt_B0_temp,omitempty" structs:"mppt_B0_temp,indirect" csv:"mppt_B0_temp"`
	// @inject_tag: structs:"mppt_B1_volt_in,indirect" csv:"mppt_B1_volt_in"
	Mppt_B1VoltIn *float32 `protobuf:"fixed32,100,opt,name=mppt_B1_volt_in,json=mpptB1VoltIn" json:"mppt_B1_volt_in,omitempty" structs:"mppt_B1_volt_in,indirect" csv:"mppt_B1_volt_in"`
	// @inject_tag: structs:"mppt_B1_volt_out,indirect" csv:"mppt_B1_volt_out"
	Mppt_B1VoltOut *float32 `protobuf:"fixed32,101,opt,name=mppt_B1_volt_out,json=mpptB1VoltOut" json:"mppt_B1_volt_out,omitempty" structs:"mppt_B1_volt_out,indirect" csv:"mppt_B1_volt_out"`
	// @inject_tag: structs:"mppt_B1_current,indirect" csv:"mppt_B1_current"
	Mppt_B1Current *float32 `protobuf:"fixed32,102,opt,name=mppt_B1_current,json=mpptB1Current" json:"mppt_B1_current,omitempty" structs:"mppt_B1_current,indirect" csv:"mppt_B1_current"`
	// @inject_tag: structs:"mppt_B1_temp,indirect" csv:"mppt_B1_temp"
	Mppt_B1Temp *float32 `protobuf:"fixed32,103,opt,name=mppt_B1_temp,json=mpptB1Temp" json:"mppt_B1_temp,omitempty" structs:"mppt_B1_temp,indirect" csv:"mppt_B1_temp"`
	// @inject_tag: structs:"mppt_C0_volt_in,indirect" csv:"mppt_C0_volt_in"
	Mppt_C0VoltIn *float32 `protobuf:"fixed32,104,opt,name=mppt_C0_volt_in,json=mpptC0VoltIn" json:"mppt_C0_volt_in,omitempty" structs:"mppt_C0_volt_in,indirect" csv:"mppt_C0_volt_in"`
	// @inject_tag: structs:"mppt_C0_volt_out,indirect" csv:"mppt_C0_volt_out"
	Mppt_C0VoltOut *float32 `protobuf:"fixed32,105,opt,name=mppt_C0_volt_out,json=mpptC0VoltOut" json:"mppt_C0_volt_out,omitempty" structs:"mppt_C0_volt_out,indirect" csv:"mppt_C0_volt_out"`
	// @inject_tag: structs:"mppt_C0_current,indirect" csv:"mppt_C0_current"
	Mppt_C0Current *float32 `protobuf:"fixed32,106,opt,name=mppt_C0_current,json=mpptC0Current" json:"mppt_C0_current,omitempty" structs:"mppt_C0_current,indirect" csv:"mppt_C0_current"`
	// @inject_tag: structs:"mppt_C0_temp,indirect" csv:"mppt_C0_temp"
	Mppt_C0Temp *float32 `protobuf:"fixed32,107,opt,name=mppt_C0_temp,json=mpptC0Temp" json:"mppt_C0_temp,omitempty" structs:"mppt_C0_temp,indirect" csv:"mppt_C0_temp"`
	// @inject_tag: structs:"mppt_C1_volt_in,indirect" csv:"mppt_C1_volt_in"
	Mppt_C1VoltIn *float32 `protobuf:"fixed32,108,opt,name=mppt_C1_volt_in,json=mpptC1VoltIn" json:"mppt_C1_volt_in,omitempty" structs:"mppt_C1_volt_in,indirect" csv:"mppt_C1_volt_in"`
	// @inject_tag: structs:"mppt_C1_volt_out,indirect" csv:"mppt_C1_volt_out"
	Mppt_C1VoltOut *float32 `protobuf:"fixed32,109,opt,name=mppt_C1_volt_out,json=mpptC1VoltOut" json:"mppt_C1_volt_out,omitempty" structs:"mppt_C1_volt_out,indirect" csv:"mppt_C1_volt_out"`
	// @inject_tag: structs:"mppt_C1_current,indirect" csv:"mppt_C1_current"
	Mppt_C1Current *float32 `protobuf:"fixed32,110,opt,name=mppt_C1_current,json=mpptC1Current" json:"mppt_C1_current,omitempty" structs:"mppt_C1_current,indirect" csv:"mppt_C1_current"`
	// @inject_tag: structs:"mppt_C1_temp,indirect" csv:"mppt_C1_temp"
	Mppt_C1Temp *float32 `protobuf:"fixed32,111,opt,name=mppt_C1_temp,json=mpptC1Temp" json:"mppt_C1_temp,omitempty" structs:"mppt_C1_temp,indirect" csv:"mppt_C1_temp"`
	// @inject_tag: structs:"mppt_D0_volt_in,indirect" csv:"mppt_D0_volt_in"
	Mppt_D0VoltIn *float32 `protobuf:"fixed32,112,opt,name=mppt_D0_volt_in,json=mpptD0VoltIn" json:"mppt_D0_volt_in,omitempty" structs:"mppt_D0_volt_in,indirect" csv:"mppt_D0_volt_in"`
	// @inject_tag: structs:"mppt_D0_volt_out,indirect" csv:"mppt_D0_volt_out"
	Mppt_D0VoltOut *float32 `protobuf:"fixed32,113,opt,name=mppt_D0_volt_out,json=mpptD0VoltOut" json:"mppt_D0_volt_out,omitempty" structs:"mppt_D0_volt_out,indirect" csv:"mppt_D0_volt_out"`
	// @inject_tag: structs:"mppt_D0_current,indirect" csv:"mppt_D0_current"
	Mppt_D0Current *float32 `protobuf:"fixed32,114,opt,name=mppt_D0_current,json=mpptD0Current" json:"mppt_D0_current,omitempty" structs:"mppt_D0_current,indirect" csv:"mppt_D0_current"`
	// @inject_tag: structs:"mppt_D0_temp,indirect" csv:"mppt_D0_temp"
	Mppt_D0Temp *float32 `protobuf:"fixed32,115,opt,name=mppt_D0_temp,json=mpptD0Temp" json:"mppt_D0_temp,omitempty" structs:"mppt_D0_temp,indirect" csv:"mppt_D0_temp"`
	// @inject_tag: structs:"mppt_D1_volt_in,indirect" csv:"mppt_D1_volt_in"
	Mppt_D1VoltIn *float32 `protobuf:"fixed32,116,opt,name=mppt_D1_volt_in,json=mpptD1VoltIn" json:"mppt_D1_volt_in,omitempty" structs:"mppt_D1_volt_in,indirect" csv:"mppt_D1_volt_in"`
	// @inject_tag: structs:"mppt_D1_volt_out,indirect" csv:"mppt_D1_volt_out"
	Mppt_D1VoltOut *float32 `protobuf:"fixed32,117,opt,name=mppt_D1_volt_out,json=mpptD1VoltOut" json:"mppt_D1_volt_out,omitempty" structs:"mppt_D1_volt_out,indirect" csv:"mppt_D1_volt_out"`
	// @inject_tag: structs:"mppt_D1_current,indirect" csv:"mppt_D1_current"
	Mppt_D1Current *float32 `protobuf:"fixed32,118,opt,name=mppt_D1_current,json=mpptD1Current" json:"mppt_D1_current,omitempty" structs:"mppt_D1_current,indirect" csv:"mppt_D1_current"`
	// @inject_tag: structs:"mppt_D1_temp,indirect" csv:"mppt_D1_temp"
	Mppt_D1Temp *float32 `protobuf:"fixed32,119,opt,name=mppt_D1_temp,json=mpptD1Temp" json:"mppt_D1_temp,omitempty" structs:"mppt_D1_temp,indirect" csv:"mppt_D1_temp"`
	// @inject_tag: structs:"cell_volt_1,indirect" csv:"cell_volt_1"
	CellVolt_1 *float32 `protobuf:"fixed32,120,opt,name=cell_volt_1,json=cellVolt1" json:"cell_volt_1,omitempty" structs:"cell_volt_1,indirect" csv:"cell_volt_1"`
	// @inject_tag: structs:"cell_volt_2,indirect" csv:"cell_volt_2"
	CellVolt_2 *float32 `protobuf:"fixed32,121,opt,name=cell_volt_2,json=cellVolt2" json:"cell_volt_2,omitempty" structs:"cell_volt_2,indirect" csv:"cell_volt_2"`
	// @inject_tag: structs:"cell_volt_3,indirect" csv:"cell_volt_3"
	CellVolt_3 *float32 `protobuf:"fixed32,122,opt,name=cell_volt_3,json=cellVolt3" json:"cell_volt_3,omitempty" structs:"cell_volt_3,indirect" csv:"cell_volt_3"`
	// @inject_tag: structs:"cell_volt_4,indirect" csv:"cell_volt_4"
	CellVolt_4 *float32 `protobuf:"fixed32,123,opt,name=cell_volt_4,json=cellVolt4" json:"cell_volt_4,omitempty" structs:"cell_volt_4,indirect" csv:"cell_volt_4"`
	// @inject_tag: structs:"cell_volt_5,indirect" csv:"cell_volt_5"
	CellVolt_5 *float32 `protobuf:"fixed32,124,opt,name=cell_volt_5,json=cellVolt5" json:"cell_volt_5,omitempty" structs:"cell_volt_5,indirect" csv:"cell_volt_5"`
	// @inject_tag: structs:"cell_volt_6,indirect" csv:"cell_volt_6"
	CellVolt_6 *float32 `protobuf:"fixed32,125,opt,name=cell_volt_6,json=cellVolt6" json:"cell_volt_6,omitempty" structs:"cell_volt_6,indirect" csv:"cell_volt_6"`
	// @inject_tag: structs:"cell_volt_7,indirect" csv:"cell_volt_7"
	CellVolt_7 *float32 `protobuf:"fixed32,126,opt,name=cell_volt_7,json=cellVolt7" json:"cell_volt_7,omitempty" structs:"cell_volt_7,indirect" csv:"cell_volt_7"`
	// @inject_tag: structs:"cell_volt_8,indirect" csv:"cell_volt_8"
	CellVolt_8 *float32 `protobuf:"fixed32,127,opt,name=cell_volt_8,json=cellVolt8" json:"cell_volt_8,omitempty" structs:"cell_volt_8,indirect" csv:"cell_volt_8"`
	// @inject_tag: structs:"cell_volt_9,indirect" csv:"cell_volt_9"
	CellVolt_9 *float32 `protobuf:"fixed32,128,opt,name=cell_volt_9,json=cellVolt9" json:"cell_volt_9,omitempty" structs:"cell_volt_9,indirect" csv:"cell_volt_9"`
	// @inject_tag: structs:"cell_volt_10,indirect" csv:"cell_volt_10"
	CellVolt_10 *float32 `protobuf:"fixed32,129,opt,name=cell_volt_10,json=cellVolt10" json:"cell_volt_10,omitempty" structs:"cell_volt_10,indirect" csv:"cell_volt_10"`
	// @inject_tag: structs:"cell_volt_11,indirect" csv:"cell_volt_11"
	CellVolt_11 *float32 `protobuf:"fixed32,130,opt,name=cell_volt_11,json=cellVolt11" json:"cell_volt_11,omitempty" structs:"cell_volt_11,indirect" csv:"cell_volt_11"`
	// @inject_tag: structs:"cell_volt_12,indirect" csv:"cell_volt_12"
	CellVolt_12 *float32 `protobuf:"fixed32,131,opt,name=cell_volt_12,json=cellVolt12" json:"cell_volt_12,omitempty" structs:"cell_volt_12,indirect" csv:"cell_volt_12"`
	// @inject_tag: structs:"cell_volt_13,indirect" csv:"cell_volt_13"
	CellVolt_13 *float32 `protobuf:"fixed32,132,opt,name=cell_volt_13,json=cellVolt13" json:"cell_volt_13,omitempty" structs:"cell_volt_13,indirect" csv:"cell_volt_13"`
	// @inject_tag: structs:"cell_volt_14,indirect" csv:"cell_volt_14"
	CellVolt_14 *float32 `protobuf:"fixed32,133,opt,name=cell_volt_14,json=cellVolt14" json:"cell_volt_14,omitempty" structs:"cell_volt_14,indirect" csv:"cell_volt_14"`
	// @inject_tag: structs:"cell_volt_15,indirect" csv:"cell_volt_15"
	CellVolt_15 *float32 `protobuf:"fixed32,134,opt,name=cell_volt_15,json=cellVolt15" json:"cell_volt_15,omitempty" structs:"cell_volt_15,indirect" csv:"cell_volt_15"`
	// @inject_tag: structs:"cell_volt_16,indirect" csv:"cell_volt_16"
	CellVolt_16 *float32 `protobuf:"fixed32,135,opt,name=cell_volt_16,json=cellVolt16" json:"cell_volt_16,omitempty" structs:"cell_volt_16,indirect" csv:"cell_volt_16"`
	// @inject_tag: structs:"cell_volt_17,indirect" csv:"cell_volt_17"
	CellVolt_17 *float32 `protobuf:"fixed32,136,opt,name=cell_volt_17,json=cellVolt17" json:"cell_volt_17,omitempty" structs:"cell_volt_17,indirect" csv:"cell_volt_17"`
	// @inject_tag: structs:"cell_volt_18,indirect" csv:"cell_volt_18"
	CellVolt_18 *float32 `protobuf:"fixed32,137,opt,name=cell_volt_18,json=cellVolt18" json:"cell_volt_18,omitempty" structs:"cell_volt_18,indirect" csv:"cell_volt_18"`
	// @inject_tag: structs:"cell_volt_19,indirect" csv:"cell_volt_19"
	CellVolt_19 *float32 `protobuf:"fixed32,138,opt,name=cell_volt_19,json=cellVolt19" json:"cell_volt_19,omitempty" structs:"cell_volt_19,indirect" csv:"cell_volt_19"`
	// @inject_tag: structs:"cell_volt_20,indirect" csv:"cell_volt_20"
	CellVolt_20 *float32 `protobuf:"fixed32,139,opt,name=cell_volt_20,json=cellVolt20" json:"cell_volt_20,omitempty" structs:"cell_volt_20,indirect" csv:"cell_volt_20"`
	// @inject_tag: structs:"cell_volt_21,indirect" csv:"cell_volt_21"
	CellVolt_21 *float32 `protobuf:"fixed32,140,opt,name=cell_volt_21,json=cellVolt21" json:"cell_volt_21,omitempty" structs:"cell_volt_21,indirect" csv:"cell_volt_21"`
	// @inject_tag: structs:"cell_volt_22,indirect" csv:"cell_volt_22"
	CellVolt_22 *float32 `protobuf:"fixed32,141,opt,name=cell_volt_22,json=cellVolt22" json:"cell_volt_22,omitempty" structs:"cell_volt_22,indirect" csv:"cell_volt_22"`
	// @inject_tag: structs:"cell_volt_23,indirect" csv:"cell_volt_23"
	CellVolt_23 *float32 `protobuf:"fixed32,142,opt,name=cell_volt_23,json=cellVolt23" json:"cell_volt_23,omitempty" structs:"cell_volt_23,indirect" csv:"cell_volt_23"`
	// @inject_tag: structs:"cell_volt_24,indirect" csv:"cell_volt_24"
	CellVolt_24 *float32 `protobuf:"fixed32,143,opt,name=cell_volt_24,json=cellVolt24" json:"cell_volt_24,omitempty" structs:"cell_volt_24,indirect" csv:"cell_volt_24"`
	// @inject_tag: structs:"cell_volt_25,indirect" csv:"cell_volt_25"
	CellVolt_25 *float32 `protobuf:"fixed32,144,opt,name=cell_volt_25,json=cellVolt25" json:"cell_volt_25,omitempty" structs:"cell_volt_25,indirect" csv:"cell_volt_25"`
	// @inject_tag: structs:"cell_volt_26,indirect" csv:"cell_volt_26"
	CellVolt_26 *float32 `protobuf:"fixed32,145,opt,name=cell_volt_26,json=cellVolt26" json:"cell_volt_26,omitempty" structs:"cell_volt_26,indirect" csv:"cell_volt_26"`
	// @inject_tag: structs:"cell_volt_27,indirect" csv:"cell_volt_27"
	CellVolt_27 *float32 `protobuf:"fixed32,146,opt,name=cell_volt_27,json=cellVolt27" json:"cell_volt_27,omitempty" structs:"cell_volt_27,indirect" csv:"cell_volt_27"`
	// @inject_tag: structs:"cell_volt_28,indirect" csv:"cell_volt_28"
	CellVolt_28 *float32 `protobuf:"fixed32,147,opt,name=cell_volt_28,json=cellVolt28" json:"cell_volt_28,omitempty" structs:"cell_volt_28,indirect" csv:"cell_volt_28"`
	// @inject_tag: structs:"cell_volt_29,indirect" csv:"cell_volt_29"
	CellVolt_29 *float32 `protobuf:"fixed32,148,opt,name=cell_volt_29,json=cellVolt29" json:"cell_volt_29,omitempty" structs:"cell_volt_29,indirect" csv:"cell_volt_29"`
	// @inject_tag: structs:"cell_volt_30,indirect" csv:"cell_volt_30"
	CellVolt_30 *float32 `protobuf:"fixed32,149,opt,name=cell_volt_30,json=cellVolt30" json:"cell_volt_30,omitempty" structs:"cell_volt_30,indirect" csv:"cell_volt_30"`
	// @inject_tag: structs:"cell_volt_31,indirect" csv:"cell_volt_31"
	CellVolt_31 *float32 `protobuf:"fixed32,150,opt,name=cell_volt_31,json=cellVolt31" json:"cell_volt_31,omitempty" structs:"cell_volt_31,indirect" csv:"cell_volt_31"`
	// @inject_tag: structs:"cell_volt_min,indirect" csv:"cell_volt_min"
	CellVoltMin *float32 `protobuf:"fixed32,151,opt,name=cell_volt_min,json=cellVoltMin" json:"cell_volt_min,omitempty" structs:"cell_volt_min,indirect" csv:"cell_volt_min"`
	// @inject_tag: structs:"cell_volt_max,indirect" csv:"cell_volt_max"
	CellVoltMax *float32 `protobuf:"fixed32,152,opt,name=cell_volt_max,json=cellVoltMax" json:"cell_volt_max,omitempty" structs:"cell_volt_max,indirect" csv:"cell_volt_max"`
	// @inject_tag: structs:"cell_volt_avg,indirect" csv:"cell_volt_avg"
	CellVoltAvg *float32 `protobuf:"fixed32,153,opt,name=cell_volt_avg,json=cellVoltAvg" json:"cell_volt_avg,omitempty" structs:"cell_volt_avg,indirect" csv:"cell_volt_avg"`
	// @inject_tag: structs:"cell_volt_diff,indirect" csv:"cell_volt_diff"
	CellVoltDiff *float32 `protobuf:"fixed32,154,opt,name=cell_volt_diff,json=cellVoltDiff" json:"cell_volt_diff,omitempty" structs:"cell_volt_diff,indirect" csv:"cell_volt_diff"`
	// @inject_tag: structs:"power_save_on,indirect" csv:"power_save_on"
	PowerSaveOn *int32 `protobuf:"varint,155,opt,name=power_save_on,json=powerSaveOn" json:"power_save_on,omitempty" structs:"power_save_on,indirect" csv:"power_save_on"`
	// @inject_tag: structs:"rearview_on,indirect" csv:"rearview_on"
	RearviewOn *int32 `protobuf:"varint,156,opt,name=rearview_on,json=rearviewOn" json:"rearview_on,omitempty" structs:"rearview_on,indirect" csv:"rearview_on"`
	// @inject_tag: structs:"mic_enabled,indirect" csv:"mic_enabled"
	MicEnabled *int32 `protobuf:"varint,157,opt,name=mic_enabled,json=micEnabled" json:"mic_enabled,omitempty" structs:"mic_enabled,indirect" csv:"mic_enabled"`
	// @inject_tag: structs:"imu_temp,indirect" csv:"imu_temp"
	ImuTemp *int32 `protobuf:"varint,158,opt,name=imu_temp,json=imuTemp" json:"imu_temp,omitempty" structs:"imu_temp,indirect" csv:"imu_temp"`
	// @inject_tag: structs:"imu_magnet_x,indirect" csv:"imu_magnet_x"
	ImuMagnetX *int32 `protobuf:"varint,159,opt,name=imu_magnet_x,json=imuMagnetX" json:"imu_magnet_x,omitempty" structs:"imu_magnet_x,indirect" csv:"imu_magnet_x"`
	// @inject_tag: structs:"imu_magnet_y,indirect" csv:"imu_magnet_y"
	ImuMagnetY *int32 `protobuf:"varint,160,opt,name=imu_magnet_y,json=imuMagnetY" json:"imu_magnet_y,omitempty" structs:"imu_magnet_y,indirect" csv:"imu_magnet_y"`
	// @inject_tag: structs:"imu_magnet_z,indirect" csv:"imu_magnet_z"
	ImuMagnetZ *int32 `protobuf:"varint,161,opt,name=imu_magnet_z,json=imuMagnetZ" json:"imu_magnet_z,omitempty" structs:"imu_magnet_z,indirect" csv:"imu_magnet_z"`
	// @inject_tag: structs:"imu_gyro_x,indirect" csv:"imu_gyro_x"
	ImuGyroX *int32 `protobuf:"varint,162,opt,name=imu_gyro_x,json=imuGyroX" json:"imu_gyro_x,omitempty" structs:"imu_gyro_x,indirect" csv:"imu_gyro_x"`
	// @inject_tag: structs:"imu_gyro_y,indirect" csv:"imu_gyro_y"
	ImuGyroY *int32 `protobuf:"varint,163,opt,name=imu_gyro_y,json=imuGyroY" json:"imu_gyro_y,omitempty" structs:"imu_gyro_y,indirect" csv:"imu_gyro_y"`
	// @inject_tag: structs:"imu_gyro_z,indirect" csv:"imu_gyro_z"
	ImuGyroZ *int32 `protobuf:"varint,164,opt,name=imu_gyro_z,json=imuGyroZ" json:"imu_gyro_z,omitempty" structs:"imu_gyro_z,indirect" csv:"imu_gyro_z"`
	// @inject_tag: structs:"imu_accel_x,indirect" csv:"imu_accel_x"
	ImuAccelX *int32 `protobuf:"varint,165,opt,name=imu_accel_x,json=imuAccelX" json:"imu_accel_x,omitempty" structs:"imu_accel_x,indirect" csv:"imu_accel_x"`
	// @inject_tag: structs:"imu_accel_y,indirect" csv:"imu_accel_y"
	ImuAccelY *int32 `protobuf:"varint,166,opt,name=imu_accel_y,json=imuAccelY" json:"imu_accel_y,omitempty" structs:"imu_accel_y,indirect" csv:"imu_accel_y"`
	// @inject_tag: structs:"imu_accel_z,indirect" csv:"imu_accel_z"
	ImuAccelZ *int32 `protobuf:"varint,167,opt,name=imu_accel_z,json=imuAccelZ" json:"imu_accel_z,omitempty" structs:"imu_accel_z,indirect" csv:"imu_accel_z"`
	// @inject_tag: structs:"bms_left_motor_controller_current,indirect" csv:"bms_left_motor_controller_current"
	BmsLeftMotorControllerCurrent *float32 `protobuf:"fixed32,168,opt,name=bms_left_motor_controller_current,json=bmsLeftMotorControllerCurrent" json:"bms_left_motor_controller_current,omitempty" structs:"bms_left_motor_controller_current,indirect" csv:"bms_left_motor_controller_current"`
	// @inject_tag: structs:"bms_right_motor_controller_current,indirect" csv:"bms_right_motor_controller_current"
	BmsRightMotorControllerCurrent *float32 `protobuf:"fixed32,169,opt,name=bms_right_motor_controller_current,json=bmsRightMotorControllerCurrent" json:"bms_right_motor_controller_current,omitempty" structs:"bms_right_motor_controller_current,indirect" csv:"bms_right_motor_controller_current"`
	// @inject_tag: structs:"bms_motor_controller_current_sum,indirect" csv:"bms_motor_controller_current_sum"
	BmsMotorControllerCurrentSum *float32 `protobuf:"fixed32,170,opt,name=bms_motor_controller_current_sum,json=bmsMotorControllerCurrentSum" json:"bms_motor_controller_current_sum,omitempty" structs:"bms_motor_controller_current_sum,indirect" csv:"bms_motor_controller_current_sum"`
	// @inject_tag: structs:"packets_per_sec,indirect" csv:"packets_per_sec"
	PacketsPerSec        *float32 `protobuf:"fixed32,171,opt,name=packets_per_sec,json=packetsPerSec" json:"packets_per_sec,omitempty" structs:"packets_per_sec,indirect" csv:"packets_per_sec"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SundaeDataMessage) Reset()         { *m = SundaeDataMessage{} }
func (m *SundaeDataMessage) String() string { return proto.CompactTextString(m) }
func (*SundaeDataMessage) ProtoMessage()    {}
func (*SundaeDataMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_sundae_f201ade6f1f0d470, []int{0}
}
func (m *SundaeDataMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SundaeDataMessage.Unmarshal(m, b)
}
func (m *SundaeDataMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SundaeDataMessage.Marshal(b, m, deterministic)
}
func (dst *SundaeDataMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SundaeDataMessage.Merge(dst, src)
}
func (m *SundaeDataMessage) XXX_Size() int {
	return xxx_messageInfo_SundaeDataMessage.Size(m)
}
func (m *SundaeDataMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SundaeDataMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SundaeDataMessage proto.InternalMessageInfo

func (m *SundaeDataMessage) GetRegenEnabled() uint32 {
	if m != nil && m.RegenEnabled != nil {
		return *m.RegenEnabled
	}
	return 0
}

func (m *SundaeDataMessage) GetRegenCommand() uint32 {
	if m != nil && m.RegenCommand != nil {
		return *m.RegenCommand
	}
	return 0
}

func (m *SundaeDataMessage) GetBatteryPower() uint32 {
	if m != nil && m.BatteryPower != nil {
		return *m.BatteryPower
	}
	return 0
}

func (m *SundaeDataMessage) GetArrayPower() float32 {
	if m != nil && m.ArrayPower != nil {
		return *m.ArrayPower
	}
	return 0
}

func (m *SundaeDataMessage) GetReverseOn() uint32 {
	if m != nil && m.ReverseOn != nil {
		return *m.ReverseOn
	}
	return 0
}

func (m *SundaeDataMessage) GetLowVoltPower() float32 {
	if m != nil && m.LowVoltPower != nil {
		return *m.LowVoltPower
	}
	return 0
}

func (m *SundaeDataMessage) GetCellReadError() int32 {
	if m != nil && m.CellReadError != nil {
		return *m.CellReadError
	}
	return 0
}

func (m *SundaeDataMessage) GetCellBleed() uint32 {
	if m != nil && m.CellBleed != nil {
		return *m.CellBleed
	}
	return 0
}

func (m *SundaeDataMessage) GetCruiseSpeed() float32 {
	if m != nil && m.CruiseSpeed != nil {
		return *m.CruiseSpeed
	}
	return 0
}

func (m *SundaeDataMessage) GetHazardLightsOn() int32 {
	if m != nil && m.HazardLightsOn != nil {
		return *m.HazardLightsOn
	}
	return 0
}

func (m *SundaeDataMessage) GetBatteryVoltage() float32 {
	if m != nil && m.BatteryVoltage != nil {
		return *m.BatteryVoltage
	}
	return 0
}

func (m *SundaeDataMessage) GetLtc6804Badpec() uint32 {
	if m != nil && m.Ltc6804Badpec != nil {
		return *m.Ltc6804Badpec
	}
	return 0
}

func (m *SundaeDataMessage) GetBmsState() uint32 {
	if m != nil && m.BmsState != nil {
		return *m.BmsState
	}
	return 0
}

func (m *SundaeDataMessage) GetChargeEnabled() int32 {
	if m != nil && m.ChargeEnabled != nil {
		return *m.ChargeEnabled
	}
	return 0
}

func (m *SundaeDataMessage) GetDischargeEnabled() int32 {
	if m != nil && m.DischargeEnabled != nil {
		return *m.DischargeEnabled
	}
	return 0
}

func (m *SundaeDataMessage) GetHighsideContactorOn() int32 {
	if m != nil && m.HighsideContactorOn != nil {
		return *m.HighsideContactorOn
	}
	return 0
}

func (m *SundaeDataMessage) GetLowsideContactorOn() int32 {
	if m != nil && m.LowsideContactorOn != nil {
		return *m.LowsideContactorOn
	}
	return 0
}

func (m *SundaeDataMessage) GetPrechargeOn() int32 {
	if m != nil && m.PrechargeOn != nil {
		return *m.PrechargeOn
	}
	return 0
}

func (m *SundaeDataMessage) GetLowVoltBusOn() int32 {
	if m != nil && m.LowVoltBusOn != nil {
		return *m.LowVoltBusOn
	}
	return 0
}

func (m *SundaeDataMessage) GetBatteryTemp_1() float32 {
	if m != nil && m.BatteryTemp_1 != nil {
		return *m.BatteryTemp_1
	}
	return 0
}

func (m *SundaeDataMessage) GetBatteryTemp_2() float32 {
	if m != nil && m.BatteryTemp_2 != nil {
		return *m.BatteryTemp_2
	}
	return 0
}

func (m *SundaeDataMessage) GetBatteryTemp_3() float32 {
	if m != nil && m.BatteryTemp_3 != nil {
		return *m.BatteryTemp_3
	}
	return 0
}

func (m *SundaeDataMessage) GetBatteryTemp_4() float32 {
	if m != nil && m.BatteryTemp_4 != nil {
		return *m.BatteryTemp_4
	}
	return 0
}

func (m *SundaeDataMessage) GetBatteryTemp_5() float32 {
	if m != nil && m.BatteryTemp_5 != nil {
		return *m.BatteryTemp_5
	}
	return 0
}

func (m *SundaeDataMessage) GetBatteryTemp_6() float32 {
	if m != nil && m.BatteryTemp_6 != nil {
		return *m.BatteryTemp_6
	}
	return 0
}

func (m *SundaeDataMessage) GetBmsPrechargeBatteryAdc() float32 {
	if m != nil && m.BmsPrechargeBatteryAdc != nil {
		return *m.BmsPrechargeBatteryAdc
	}
	return 0
}

func (m *SundaeDataMessage) GetBmsPrechargeCarAdc() float32 {
	if m != nil && m.BmsPrechargeCarAdc != nil {
		return *m.BmsPrechargeCarAdc
	}
	return 0
}

func (m *SundaeDataMessage) GetLowVoltOutputCurrent() float32 {
	if m != nil && m.LowVoltOutputCurrent != nil {
		return *m.LowVoltOutputCurrent
	}
	return 0
}

func (m *SundaeDataMessage) GetArrayCurrent() float32 {
	if m != nil && m.ArrayCurrent != nil {
		return *m.ArrayCurrent
	}
	return 0
}

func (m *SundaeDataMessage) GetBatteryCurrent() float32 {
	if m != nil && m.BatteryCurrent != nil {
		return *m.BatteryCurrent
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorControllerPower() float32 {
	if m != nil && m.LeftMotorControllerPower != nil {
		return *m.LeftMotorControllerPower
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorControllerPower() float32 {
	if m != nil && m.RightMotorControllerPower != nil {
		return *m.RightMotorControllerPower
	}
	return 0
}

func (m *SundaeDataMessage) GetAmpHours() float32 {
	if m != nil && m.AmpHours != nil {
		return *m.AmpHours
	}
	return 0
}

func (m *SundaeDataMessage) GetHeadLightsOn() int32 {
	if m != nil && m.HeadLightsOn != nil {
		return *m.HeadLightsOn
	}
	return 0
}

func (m *SundaeDataMessage) GetBrakeLightsOn() int32 {
	if m != nil && m.BrakeLightsOn != nil {
		return *m.BrakeLightsOn
	}
	return 0
}

func (m *SundaeDataMessage) GetRightBlinkerOn() int32 {
	if m != nil && m.RightBlinkerOn != nil {
		return *m.RightBlinkerOn
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftBlinkerOn() int32 {
	if m != nil && m.LeftBlinkerOn != nil {
		return *m.LeftBlinkerOn
	}
	return 0
}

func (m *SundaeDataMessage) GetBrakePressed() int32 {
	if m != nil && m.BrakePressed != nil {
		return *m.BrakePressed
	}
	return 0
}

func (m *SundaeDataMessage) GetThrottlePressed() int32 {
	if m != nil && m.ThrottlePressed != nil {
		return *m.ThrottlePressed
	}
	return 0
}

func (m *SundaeDataMessage) GetDriveMode() uint32 {
	if m != nil && m.DriveMode != nil {
		return *m.DriveMode
	}
	return 0
}

func (m *SundaeDataMessage) GetMotorControllerEnabled() int32 {
	if m != nil && m.MotorControllerEnabled != nil {
		return *m.MotorControllerEnabled
	}
	return 0
}

func (m *SundaeDataMessage) GetMotorControllerSpeed() float32 {
	if m != nil && m.MotorControllerSpeed != nil {
		return *m.MotorControllerSpeed
	}
	return 0
}

func (m *SundaeDataMessage) GetMotorControllerRpm() float32 {
	if m != nil && m.MotorControllerRpm != nil {
		return *m.MotorControllerRpm
	}
	return 0
}

func (m *SundaeDataMessage) GetAvgOdometer() float32 {
	if m != nil && m.AvgOdometer != nil {
		return *m.AvgOdometer
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorTemp() float32 {
	if m != nil && m.LeftMotorTemp != nil {
		return *m.LeftMotorTemp
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorTemp() float32 {
	if m != nil && m.RightMotorTemp != nil {
		return *m.RightMotorTemp
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorControllerTemp() float32 {
	if m != nil && m.LeftMotorControllerTemp != nil {
		return *m.LeftMotorControllerTemp
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorControllerTemp() float32 {
	if m != nil && m.RightMotorControllerTemp != nil {
		return *m.RightMotorControllerTemp
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorControllerAlive() float32 {
	if m != nil && m.LeftMotorControllerAlive != nil {
		return *m.LeftMotorControllerAlive
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorControllerAlive() float32 {
	if m != nil && m.RightMotorControllerAlive != nil {
		return *m.RightMotorControllerAlive
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorControllerCurrent() float32 {
	if m != nil && m.LeftMotorControllerCurrent != nil {
		return *m.LeftMotorControllerCurrent
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorControllerCurrent() float32 {
	if m != nil && m.RightMotorControllerCurrent != nil {
		return *m.RightMotorControllerCurrent
	}
	return 0
}

func (m *SundaeDataMessage) GetMotorControllerCurrentDiff() float32 {
	if m != nil && m.MotorControllerCurrentDiff != nil {
		return *m.MotorControllerCurrentDiff
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorControllerError() uint32 {
	if m != nil && m.LeftMotorControllerError != nil {
		return *m.LeftMotorControllerError
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorControllerError() uint32 {
	if m != nil && m.RightMotorControllerError != nil {
		return *m.RightMotorControllerError
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorControllerLimit() uint32 {
	if m != nil && m.LeftMotorControllerLimit != nil {
		return *m.LeftMotorControllerLimit
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorControllerLimit() uint32 {
	if m != nil && m.RightMotorControllerLimit != nil {
		return *m.RightMotorControllerLimit
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorControllerRxErrorCount() uint32 {
	if m != nil && m.LeftMotorControllerRxErrorCount != nil {
		return *m.LeftMotorControllerRxErrorCount
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorControllerRxErrorCount() uint32 {
	if m != nil && m.RightMotorControllerRxErrorCount != nil {
		return *m.RightMotorControllerRxErrorCount
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorControllerTxErrorCount() uint32 {
	if m != nil && m.LeftMotorControllerTxErrorCount != nil {
		return *m.LeftMotorControllerTxErrorCount
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorControllerTxErrorCount() uint32 {
	if m != nil && m.RightMotorControllerTxErrorCount != nil {
		return *m.RightMotorControllerTxErrorCount
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorControllerBusVoltage() float32 {
	if m != nil && m.LeftMotorControllerBusVoltage != nil {
		return *m.LeftMotorControllerBusVoltage
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorControllerBusVoltage() float32 {
	if m != nil && m.RightMotorControllerBusVoltage != nil {
		return *m.RightMotorControllerBusVoltage
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorController_15VVoltage() float32 {
	if m != nil && m.LeftMotorController_15VVoltage != nil {
		return *m.LeftMotorController_15VVoltage
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorController_15VVoltage() float32 {
	if m != nil && m.RightMotorController_15VVoltage != nil {
		return *m.RightMotorController_15VVoltage
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorController_3V3Voltage() float32 {
	if m != nil && m.LeftMotorController_3V3Voltage != nil {
		return *m.LeftMotorController_3V3Voltage
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorController_3V3Voltage() float32 {
	if m != nil && m.RightMotorController_3V3Voltage != nil {
		return *m.RightMotorController_3V3Voltage
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorController_1V9Voltage() float32 {
	if m != nil && m.LeftMotorController_1V9Voltage != nil {
		return *m.LeftMotorController_1V9Voltage
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorController_1V9Voltage() float32 {
	if m != nil && m.RightMotorController_1V9Voltage != nil {
		return *m.RightMotorController_1V9Voltage
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorControllerDspTemp() float32 {
	if m != nil && m.LeftMotorControllerDspTemp != nil {
		return *m.LeftMotorControllerDspTemp
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorControllerDspTemp() float32 {
	if m != nil && m.RightMotorControllerDspTemp != nil {
		return *m.RightMotorControllerDspTemp
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorControllerPhaseCurrent() float32 {
	if m != nil && m.LeftMotorControllerPhaseCurrent != nil {
		return *m.LeftMotorControllerPhaseCurrent
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorControllerPhaseCurrent() float32 {
	if m != nil && m.RightMotorControllerPhaseCurrent != nil {
		return *m.RightMotorControllerPhaseCurrent
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorRpmCommand() float32 {
	if m != nil && m.LeftMotorRpmCommand != nil {
		return *m.LeftMotorRpmCommand
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorRpmCommand() float32 {
	if m != nil && m.RightMotorRpmCommand != nil {
		return *m.RightMotorRpmCommand
	}
	return 0
}

func (m *SundaeDataMessage) GetLeftMotorCurrentCommand() float32 {
	if m != nil && m.LeftMotorCurrentCommand != nil {
		return *m.LeftMotorCurrentCommand
	}
	return 0
}

func (m *SundaeDataMessage) GetRightMotorCurrentCommand() float32 {
	if m != nil && m.RightMotorCurrentCommand != nil {
		return *m.RightMotorCurrentCommand
	}
	return 0
}

func (m *SundaeDataMessage) GetGpsTime() int64 {
	if m != nil && m.GpsTime != nil {
		return *m.GpsTime
	}
	return 0
}

func (m *SundaeDataMessage) GetGpsLatitude() float32 {
	if m != nil && m.GpsLatitude != nil {
		return *m.GpsLatitude
	}
	return 0
}

func (m *SundaeDataMessage) GetGpsLongitude() float32 {
	if m != nil && m.GpsLongitude != nil {
		return *m.GpsLongitude
	}
	return 0
}

func (m *SundaeDataMessage) GetGpsSpeed() float32 {
	if m != nil && m.GpsSpeed != nil {
		return *m.GpsSpeed
	}
	return 0
}

func (m *SundaeDataMessage) GetGpsAltitude() float32 {
	if m != nil && m.GpsAltitude != nil {
		return *m.GpsAltitude
	}
	return 0
}

func (m *SundaeDataMessage) GetGpsBearing() float32 {
	if m != nil && m.GpsBearing != nil {
		return *m.GpsBearing
	}
	return 0
}

func (m *SundaeDataMessage) GetLedState() int32 {
	if m != nil && m.LedState != nil {
		return *m.LedState
	}
	return 0
}

func (m *SundaeDataMessage) GetMpptArrayPower() float32 {
	if m != nil && m.MpptArrayPower != nil {
		return *m.MpptArrayPower
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_A0VoltIn() float32 {
	if m != nil && m.Mppt_A0VoltIn != nil {
		return *m.Mppt_A0VoltIn
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_A0VoltOut() float32 {
	if m != nil && m.Mppt_A0VoltOut != nil {
		return *m.Mppt_A0VoltOut
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_A0Current() float32 {
	if m != nil && m.Mppt_A0Current != nil {
		return *m.Mppt_A0Current
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_A0Temp() float32 {
	if m != nil && m.Mppt_A0Temp != nil {
		return *m.Mppt_A0Temp
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_A1VoltIn() float32 {
	if m != nil && m.Mppt_A1VoltIn != nil {
		return *m.Mppt_A1VoltIn
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_A1VoltOut() float32 {
	if m != nil && m.Mppt_A1VoltOut != nil {
		return *m.Mppt_A1VoltOut
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_A1Current() float32 {
	if m != nil && m.Mppt_A1Current != nil {
		return *m.Mppt_A1Current
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_A1Temp() float32 {
	if m != nil && m.Mppt_A1Temp != nil {
		return *m.Mppt_A1Temp
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_B0VoltIn() float32 {
	if m != nil && m.Mppt_B0VoltIn != nil {
		return *m.Mppt_B0VoltIn
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_B0VoltOut() float32 {
	if m != nil && m.Mppt_B0VoltOut != nil {
		return *m.Mppt_B0VoltOut
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_B0Current() float32 {
	if m != nil && m.Mppt_B0Current != nil {
		return *m.Mppt_B0Current
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_B0Temp() float32 {
	if m != nil && m.Mppt_B0Temp != nil {
		return *m.Mppt_B0Temp
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_B1VoltIn() float32 {
	if m != nil && m.Mppt_B1VoltIn != nil {
		return *m.Mppt_B1VoltIn
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_B1VoltOut() float32 {
	if m != nil && m.Mppt_B1VoltOut != nil {
		return *m.Mppt_B1VoltOut
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_B1Current() float32 {
	if m != nil && m.Mppt_B1Current != nil {
		return *m.Mppt_B1Current
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_B1Temp() float32 {
	if m != nil && m.Mppt_B1Temp != nil {
		return *m.Mppt_B1Temp
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_C0VoltIn() float32 {
	if m != nil && m.Mppt_C0VoltIn != nil {
		return *m.Mppt_C0VoltIn
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_C0VoltOut() float32 {
	if m != nil && m.Mppt_C0VoltOut != nil {
		return *m.Mppt_C0VoltOut
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_C0Current() float32 {
	if m != nil && m.Mppt_C0Current != nil {
		return *m.Mppt_C0Current
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_C0Temp() float32 {
	if m != nil && m.Mppt_C0Temp != nil {
		return *m.Mppt_C0Temp
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_C1VoltIn() float32 {
	if m != nil && m.Mppt_C1VoltIn != nil {
		return *m.Mppt_C1VoltIn
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_C1VoltOut() float32 {
	if m != nil && m.Mppt_C1VoltOut != nil {
		return *m.Mppt_C1VoltOut
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_C1Current() float32 {
	if m != nil && m.Mppt_C1Current != nil {
		return *m.Mppt_C1Current
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_C1Temp() float32 {
	if m != nil && m.Mppt_C1Temp != nil {
		return *m.Mppt_C1Temp
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_D0VoltIn() float32 {
	if m != nil && m.Mppt_D0VoltIn != nil {
		return *m.Mppt_D0VoltIn
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_D0VoltOut() float32 {
	if m != nil && m.Mppt_D0VoltOut != nil {
		return *m.Mppt_D0VoltOut
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_D0Current() float32 {
	if m != nil && m.Mppt_D0Current != nil {
		return *m.Mppt_D0Current
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_D0Temp() float32 {
	if m != nil && m.Mppt_D0Temp != nil {
		return *m.Mppt_D0Temp
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_D1VoltIn() float32 {
	if m != nil && m.Mppt_D1VoltIn != nil {
		return *m.Mppt_D1VoltIn
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_D1VoltOut() float32 {
	if m != nil && m.Mppt_D1VoltOut != nil {
		return *m.Mppt_D1VoltOut
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_D1Current() float32 {
	if m != nil && m.Mppt_D1Current != nil {
		return *m.Mppt_D1Current
	}
	return 0
}

func (m *SundaeDataMessage) GetMppt_D1Temp() float32 {
	if m != nil && m.Mppt_D1Temp != nil {
		return *m.Mppt_D1Temp
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_1() float32 {
	if m != nil && m.CellVolt_1 != nil {
		return *m.CellVolt_1
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_2() float32 {
	if m != nil && m.CellVolt_2 != nil {
		return *m.CellVolt_2
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_3() float32 {
	if m != nil && m.CellVolt_3 != nil {
		return *m.CellVolt_3
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_4() float32 {
	if m != nil && m.CellVolt_4 != nil {
		return *m.CellVolt_4
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_5() float32 {
	if m != nil && m.CellVolt_5 != nil {
		return *m.CellVolt_5
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_6() float32 {
	if m != nil && m.CellVolt_6 != nil {
		return *m.CellVolt_6
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_7() float32 {
	if m != nil && m.CellVolt_7 != nil {
		return *m.CellVolt_7
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_8() float32 {
	if m != nil && m.CellVolt_8 != nil {
		return *m.CellVolt_8
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_9() float32 {
	if m != nil && m.CellVolt_9 != nil {
		return *m.CellVolt_9
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_10() float32 {
	if m != nil && m.CellVolt_10 != nil {
		return *m.CellVolt_10
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_11() float32 {
	if m != nil && m.CellVolt_11 != nil {
		return *m.CellVolt_11
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_12() float32 {
	if m != nil && m.CellVolt_12 != nil {
		return *m.CellVolt_12
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_13() float32 {
	if m != nil && m.CellVolt_13 != nil {
		return *m.CellVolt_13
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_14() float32 {
	if m != nil && m.CellVolt_14 != nil {
		return *m.CellVolt_14
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_15() float32 {
	if m != nil && m.CellVolt_15 != nil {
		return *m.CellVolt_15
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_16() float32 {
	if m != nil && m.CellVolt_16 != nil {
		return *m.CellVolt_16
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_17() float32 {
	if m != nil && m.CellVolt_17 != nil {
		return *m.CellVolt_17
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_18() float32 {
	if m != nil && m.CellVolt_18 != nil {
		return *m.CellVolt_18
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_19() float32 {
	if m != nil && m.CellVolt_19 != nil {
		return *m.CellVolt_19
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_20() float32 {
	if m != nil && m.CellVolt_20 != nil {
		return *m.CellVolt_20
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_21() float32 {
	if m != nil && m.CellVolt_21 != nil {
		return *m.CellVolt_21
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_22() float32 {
	if m != nil && m.CellVolt_22 != nil {
		return *m.CellVolt_22
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_23() float32 {
	if m != nil && m.CellVolt_23 != nil {
		return *m.CellVolt_23
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_24() float32 {
	if m != nil && m.CellVolt_24 != nil {
		return *m.CellVolt_24
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_25() float32 {
	if m != nil && m.CellVolt_25 != nil {
		return *m.CellVolt_25
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_26() float32 {
	if m != nil && m.CellVolt_26 != nil {
		return *m.CellVolt_26
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_27() float32 {
	if m != nil && m.CellVolt_27 != nil {
		return *m.CellVolt_27
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_28() float32 {
	if m != nil && m.CellVolt_28 != nil {
		return *m.CellVolt_28
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_29() float32 {
	if m != nil && m.CellVolt_29 != nil {
		return *m.CellVolt_29
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_30() float32 {
	if m != nil && m.CellVolt_30 != nil {
		return *m.CellVolt_30
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVolt_31() float32 {
	if m != nil && m.CellVolt_31 != nil {
		return *m.CellVolt_31
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVoltMin() float32 {
	if m != nil && m.CellVoltMin != nil {
		return *m.CellVoltMin
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVoltMax() float32 {
	if m != nil && m.CellVoltMax != nil {
		return *m.CellVoltMax
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVoltAvg() float32 {
	if m != nil && m.CellVoltAvg != nil {
		return *m.CellVoltAvg
	}
	return 0
}

func (m *SundaeDataMessage) GetCellVoltDiff() float32 {
	if m != nil && m.CellVoltDiff != nil {
		return *m.CellVoltDiff
	}
	return 0
}

func (m *SundaeDataMessage) GetPowerSaveOn() int32 {
	if m != nil && m.PowerSaveOn != nil {
		return *m.PowerSaveOn
	}
	return 0
}

func (m *SundaeDataMessage) GetRearviewOn() int32 {
	if m != nil && m.RearviewOn != nil {
		return *m.RearviewOn
	}
	return 0
}

func (m *SundaeDataMessage) GetMicEnabled() int32 {
	if m != nil && m.MicEnabled != nil {
		return *m.MicEnabled
	}
	return 0
}

func (m *SundaeDataMessage) GetImuTemp() int32 {
	if m != nil && m.ImuTemp != nil {
		return *m.ImuTemp
	}
	return 0
}

func (m *SundaeDataMessage) GetImuMagnetX() int32 {
	if m != nil && m.ImuMagnetX != nil {
		return *m.ImuMagnetX
	}
	return 0
}

func (m *SundaeDataMessage) GetImuMagnetY() int32 {
	if m != nil && m.ImuMagnetY != nil {
		return *m.ImuMagnetY
	}
	return 0
}

func (m *SundaeDataMessage) GetImuMagnetZ() int32 {
	if m != nil && m.ImuMagnetZ != nil {
		return *m.ImuMagnetZ
	}
	return 0
}

func (m *SundaeDataMessage) GetImuGyroX() int32 {
	if m != nil && m.ImuGyroX != nil {
		return *m.ImuGyroX
	}
	return 0
}

func (m *SundaeDataMessage) GetImuGyroY() int32 {
	if m != nil && m.ImuGyroY != nil {
		return *m.ImuGyroY
	}
	return 0
}

func (m *SundaeDataMessage) GetImuGyroZ() int32 {
	if m != nil && m.ImuGyroZ != nil {
		return *m.ImuGyroZ
	}
	return 0
}

func (m *SundaeDataMessage) GetImuAccelX() int32 {
	if m != nil && m.ImuAccelX != nil {
		return *m.ImuAccelX
	}
	return 0
}

func (m *SundaeDataMessage) GetImuAccelY() int32 {
	if m != nil && m.ImuAccelY != nil {
		return *m.ImuAccelY
	}
	return 0
}

func (m *SundaeDataMessage) GetImuAccelZ() int32 {
	if m != nil && m.ImuAccelZ != nil {
		return *m.ImuAccelZ
	}
	return 0
}

func (m *SundaeDataMessage) GetBmsLeftMotorControllerCurrent() float32 {
	if m != nil && m.BmsLeftMotorControllerCurrent != nil {
		return *m.BmsLeftMotorControllerCurrent
	}
	return 0
}

func (m *SundaeDataMessage) GetBmsRightMotorControllerCurrent() float32 {
	if m != nil && m.BmsRightMotorControllerCurrent != nil {
		return *m.BmsRightMotorControllerCurrent
	}
	return 0
}

func (m *SundaeDataMessage) GetBmsMotorControllerCurrentSum() float32 {
	if m != nil && m.BmsMotorControllerCurrentSum != nil {
		return *m.BmsMotorControllerCurrentSum
	}
	return 0
}

func (m *SundaeDataMessage) GetPacketsPerSec() float32 {
	if m != nil && m.PacketsPerSec != nil {
		return *m.PacketsPerSec
	}
	return 0
}

func init() {
	proto.RegisterType((*SundaeDataMessage)(nil), "SundaeDataMessage")
}

func init() { proto.RegisterFile("sundae.proto", fileDescriptor_sundae_f201ade6f1f0d470) }

var fileDescriptor_sundae_f201ade6f1f0d470 = []byte{
	// 2299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x99, 0x79, 0x5f, 0xdc, 0xc6,
	0x19, 0xc7, 0x3f, 0x24, 0x4d, 0x8d, 0x07, 0x30, 0x58, 0xbe, 0x1e, 0x9b, 0x80, 0xc1, 0x27, 0x69,
	0xda, 0x94, 0xd5, 0xb2, 0x1c, 0x49, 0xdd, 0x94, 0xdd, 0x75, 0x6d, 0x27, 0x10, 0x28, 0xb8, 0xae,
	0xed, 0x1e, 0xea, 0xac, 0x34, 0x08, 0xd5, 0xba, 0x3a, 0x92, 0x16, 0x70, 0xef, 0xfb, 0xbe, 0xef,
	0xfb, 0xbe, 0xdf, 0x45, 0x5f, 0x59, 0x3e, 0x33, 0xa3, 0x63, 0x34, 0x92, 0x70, 0xfe, 0xe4, 0x79,
	0xbe, 0xcf, 0x33, 0x3f, 0xfd, 0x76, 0x66, 0x34, 0x1a, 0xd0, 0x78, 0x94, 0xf8, 0x16, 0x26, 0xaf,
	0x84, 0x34, 0x88, 0x83, 0x2b, 0xff, 0x7f, 0x15, 0x9d, 0xde, 0xe5, 0x81, 0x3e, 0x8e, 0xf1, 0x26,
	0x89, 0x22, 0x6c, 0x13, 0xed, 0x2a, 0x9a, 0xa0, 0xc4, 0x26, 0xbe, 0x41, 0x7c, 0x3c, 0x70, 0x89,
	0x05, 0x23, 0x73, 0x23, 0x0b, 0x13, 0x3b, 0xe3, 0x3c, 0x78, 0x5b, 0xc4, 0x0a, 0xc8, 0x0c, 0x3c,
	0x0f, 0xfb, 0x16, 0x3c, 0x27, 0x41, 0x3d, 0x11, 0x63, 0xd0, 0x00, 0xc7, 0x31, 0xa1, 0x47, 0x46,
	0x18, 0x1c, 0x10, 0x0a, 0xcf, 0x0b, 0x28, 0x0d, 0x6e, 0xb3, 0x98, 0x76, 0x19, 0x8d, 0x61, 0x4a,
	0x71, 0x86, 0xbc, 0x6b, 0x6e, 0x64, 0xe1, 0xb9, 0x1d, 0xc4, 0x43, 0x02, 0x98, 0x41, 0x88, 0x92,
	0x21, 0xa1, 0x11, 0x31, 0x02, 0x1f, 0x5e, 0xe0, 0x2d, 0x4e, 0xa6, 0x91, 0x2d, 0x5f, 0xbb, 0x86,
	0x4e, 0xb9, 0xc1, 0x81, 0x31, 0x0c, 0xdc, 0x38, 0x6d, 0xf1, 0x6e, 0xde, 0x62, 0xdc, 0x0d, 0x0e,
	0x1e, 0x04, 0x6e, 0x2c, 0x9a, 0xdc, 0x40, 0x93, 0x26, 0x71, 0x5d, 0x83, 0x12, 0x6c, 0x19, 0x84,
	0xd2, 0x80, 0xc2, 0x89, 0xb9, 0x91, 0x85, 0x17, 0x76, 0x26, 0x58, 0x78, 0x87, 0x60, 0xeb, 0x36,
	0x0b, 0xb2, 0xc1, 0x38, 0x37, 0x70, 0x09, 0xb1, 0x60, 0x54, 0x0c, 0xc6, 0x22, 0x5d, 0x16, 0xd0,
	0xe6, 0xd1, 0xb8, 0x49, 0x13, 0x27, 0x22, 0x46, 0x14, 0x32, 0xe0, 0x24, 0x1f, 0x6a, 0x4c, 0xc4,
	0x76, 0x59, 0x48, 0x5b, 0x40, 0x53, 0xfb, 0xf8, 0x29, 0xa6, 0x96, 0xe1, 0x3a, 0xf6, 0x7e, 0x1c,
	0x31, 0xd1, 0x88, 0x0f, 0x75, 0x4a, 0xc4, 0x37, 0x78, 0x78, 0xcb, 0xd7, 0x6e, 0xa2, 0xc9, 0xcc,
	0x1e, 0xa6, 0x1e, 0xdb, 0x04, 0xc6, 0x78, 0xbf, 0x53, 0x69, 0xf8, 0x81, 0x88, 0x6a, 0xd7, 0xd1,
	0x29, 0x37, 0x36, 0x97, 0x57, 0x17, 0x97, 0x8c, 0x01, 0xb6, 0x42, 0x62, 0xc2, 0x38, 0x17, 0x36,
	0x91, 0x46, 0xbb, 0x3c, 0xa8, 0x4d, 0xa3, 0x93, 0x03, 0x2f, 0x32, 0xa2, 0x18, 0xc7, 0x04, 0x26,
	0x38, 0x31, 0x3a, 0xf0, 0xa2, 0x5d, 0xf6, 0x37, 0xeb, 0x61, 0xee, 0x63, 0x6a, 0x93, 0xfc, 0x67,
	0x3d, 0x95, 0x3e, 0x3f, 0x8f, 0x66, 0xbf, 0xeb, 0xcb, 0xe8, 0xb4, 0xe5, 0x44, 0x0a, 0x39, 0xc9,
	0xc9, 0xa9, 0x3c, 0x91, 0xc1, 0x3a, 0x3a, 0xb7, 0xef, 0xd8, 0xfb, 0x91, 0x63, 0x11, 0xc3, 0x0c,
	0xfc, 0x18, 0x9b, 0x71, 0x40, 0xd9, 0xf3, 0x4e, 0xf1, 0x82, 0x33, 0x59, 0xb2, 0x97, 0xe5, 0xb6,
	0x7c, 0x6d, 0x11, 0x9d, 0x75, 0x83, 0x83, 0x6a, 0xc9, 0x69, 0x5e, 0xa2, 0xa5, 0x39, 0xb9, 0x62,
	0x1e, 0x8d, 0x87, 0x94, 0xa4, 0x92, 0x02, 0x1f, 0x34, 0x4e, 0x8e, 0xe5, 0xb1, 0x2d, 0x5f, 0xbb,
	0x8e, 0x26, 0xf3, 0x39, 0x30, 0x48, 0xb8, 0xe5, 0x67, 0x38, 0x95, 0x4d, 0x82, 0x6e, 0x12, 0x89,
	0xa9, 0x92, 0x19, 0x1e, 0x13, 0x2f, 0x34, 0x5a, 0x70, 0x56, 0x4c, 0x95, 0x34, 0x7a, 0x9f, 0x78,
	0x61, 0xab, 0x42, 0xe9, 0x70, 0xae, 0x42, 0xe9, 0x15, 0xaa, 0x0d, 0xe7, 0x2b, 0x54, 0xbb, 0x42,
	0x2d, 0xc1, 0x85, 0x0a, 0xb5, 0x54, 0xa1, 0x3a, 0x00, 0x15, 0xaa, 0x53, 0xa1, 0x96, 0xe1, 0x62,
	0x85, 0x5a, 0xd6, 0xd6, 0xd0, 0x45, 0x36, 0x09, 0x0a, 0xc7, 0xb2, 0x1a, 0x6c, 0x99, 0x70, 0x89,
	0x17, 0x9c, 0x1f, 0x78, 0xd1, 0x76, 0x96, 0xef, 0x8a, 0xf4, 0xba, 0x65, 0x6a, 0x2d, 0x74, 0xae,
	0x5c, 0x6a, 0x62, 0xca, 0xcb, 0xa6, 0x79, 0x99, 0x26, 0x97, 0xf5, 0x30, 0x65, 0x25, 0x1d, 0x74,
	0x21, 0x37, 0x3e, 0x48, 0xe2, 0x30, 0x89, 0x0d, 0x33, 0xa1, 0x94, 0xf8, 0x31, 0xcc, 0xf0, 0xa2,
	0xb3, 0xe9, 0x0f, 0xb0, 0xc5, 0x93, 0x3d, 0x91, 0x63, 0x1b, 0x83, 0x58, 0xf3, 0x19, 0x3c, 0x2b,
	0x9e, 0x84, 0x07, 0x33, 0x48, 0x5a, 0x1e, 0x19, 0x76, 0xb9, 0xb4, 0x3c, 0x32, 0xf0, 0x16, 0x9a,
	0x76, 0xc9, 0x5e, 0x6c, 0x78, 0x01, 0x9b, 0x4b, 0x6c, 0x56, 0xd1, 0xc0, 0x75, 0x09, 0x4d, 0xb7,
	0x83, 0x39, 0x5e, 0x04, 0x0c, 0xd9, 0x64, 0x44, 0x2f, 0x07, 0xc4, 0xd6, 0xf0, 0x3a, 0x7a, 0x91,
	0xb2, 0x25, 0xd9, 0x54, 0x3f, 0xcf, 0xeb, 0x2f, 0x72, 0xa6, 0xb6, 0xc1, 0x34, 0x3a, 0x89, 0xbd,
	0xd0, 0xd8, 0x0f, 0x12, 0x1a, 0xc1, 0x15, 0x4e, 0x8f, 0x62, 0x2f, 0xbc, 0xcb, 0xfe, 0x66, 0xbf,
	0xda, 0x3e, 0xdb, 0x73, 0x8a, 0xcd, 0xe0, 0xaa, 0x98, 0x99, 0x2c, 0x9a, 0x6f, 0x05, 0x37, 0xd0,
	0xe4, 0x80, 0xe2, 0x27, 0x44, 0xc2, 0xae, 0x89, 0xe5, 0xc9, 0xc3, 0x39, 0xb7, 0x80, 0xa6, 0x84,
	0xd6, 0x81, 0xeb, 0xf8, 0x4f, 0x08, 0x5f, 0x39, 0xd7, 0xc5, 0xe6, 0xc2, 0xe3, 0x5d, 0x11, 0x16,
	0x1d, 0xb9, 0x29, 0x12, 0x78, 0x43, 0x74, 0x64, 0xe1, 0x82, 0x63, 0x7b, 0x34, 0x1f, 0x39, 0xa4,
	0x24, 0x8a, 0x88, 0x05, 0x37, 0x85, 0x3c, 0x1e, 0xdc, 0x16, 0x31, 0xed, 0x25, 0x34, 0x15, 0xef,
	0xd3, 0x20, 0x8e, 0xdd, 0x82, 0x5b, 0xe0, 0xdc, 0x64, 0x16, 0xcf, 0xd0, 0x19, 0x84, 0x2c, 0xea,
	0x0c, 0x89, 0xe1, 0x05, 0x16, 0x81, 0x97, 0xc4, 0x06, 0xca, 0x23, 0x9b, 0x81, 0x45, 0xb4, 0x55,
	0x04, 0x15, 0x9b, 0xb3, 0x6d, 0xe6, 0x3d, 0xbc, 0xe3, 0x79, 0xaf, 0xec, 0x71, 0xb6, 0xd9, 0x2c,
	0xa1, 0xf3, 0x95, 0x4a, 0xb1, 0x09, 0xbf, 0x2c, 0x66, 0x9a, 0x52, 0x27, 0x76, 0xe3, 0x45, 0x74,
	0xb6, 0x52, 0x45, 0x43, 0x0f, 0xde, 0x2b, 0xa6, 0xb4, 0x52, 0xb3, 0x13, 0x7a, 0x6c, 0xbb, 0xc1,
	0x43, 0xdb, 0x08, 0xac, 0xc0, 0x23, 0x31, 0xa1, 0xf0, 0x3e, 0xb1, 0xc5, 0xe3, 0xa1, 0xbd, 0x95,
	0x86, 0x72, 0x6f, 0x45, 0x67, 0xb6, 0x18, 0xe1, 0x15, 0x4e, 0x4d, 0xe4, 0x93, 0x8c, 0x2d, 0xc6,
	0xe2, 0xd7, 0x92, 0xc0, 0xf7, 0x8b, 0x29, 0x5c, 0xcc, 0x26, 0x4e, 0xbe, 0x86, 0x2e, 0xd5, 0x4f,
	0x61, 0x5e, 0xb3, 0xc8, 0x6b, 0x2e, 0xd4, 0xcc, 0x60, 0x5e, 0x7c, 0x0b, 0x4d, 0x37, 0x4c, 0x60,
	0x5e, 0xdd, 0x12, 0xf3, 0xbf, 0x6e, 0xfe, 0x66, 0xe5, 0xf5, 0x63, 0x63, 0xd7, 0x19, 0x12, 0xd0,
	0x1b, 0x97, 0xcf, 0x3a, 0xcb, 0x1f, 0xb3, 0x7c, 0x44, 0x7d, 0xbb, 0x79, 0xf9, 0x88, 0x06, 0xeb,
	0x68, 0xa6, 0x7e, 0xfc, 0x6c, 0xd5, 0x2f, 0xf1, 0x0e, 0x97, 0x6a, 0x14, 0x64, 0x3b, 0x40, 0x0f,
	0xcd, 0x36, 0x68, 0xc8, 0x7a, 0x74, 0x78, 0x8f, 0xe9, 0x3a, 0x15, 0x59, 0x93, 0x75, 0x34, 0xd3,
	0x54, 0x6e, 0x58, 0xce, 0xde, 0x1e, 0x2c, 0x0b, 0x1d, 0x5e, 0x6d, 0x79, 0xdf, 0xd9, 0xdb, 0x6b,
	0xb6, 0x52, 0x9c, 0x38, 0x56, 0xf8, 0x6a, 0xa8, 0xb3, 0x52, 0x1c, 0x3e, 0x9a, 0xad, 0x14, 0xf5,
	0xab, 0xbc, 0xbe, 0xd6, 0x4a, 0xd1, 0xa0, 0x71, 0x7c, 0xd7, 0xf1, 0x9c, 0x18, 0xd6, 0x1a, 0xc7,
	0xdf, 0x60, 0xf9, 0x63, 0xc6, 0x17, 0xf5, 0xaf, 0x36, 0x8f, 0x2f, 0x1a, 0x6c, 0xa2, 0x6b, 0xf5,
	0xe3, 0xd3, 0x43, 0xf1, 0x08, 0x86, 0x19, 0x24, 0x7e, 0x0c, 0xaf, 0xf1, 0x46, 0x97, 0x6b, 0x84,
	0xec, 0x1c, 0xf2, 0x27, 0xe9, 0x31, 0x4c, 0xdb, 0x42, 0xd7, 0x1b, 0xf4, 0x28, 0xfd, 0x3e, 0xc0,
	0xfb, 0xcd, 0xd5, 0x09, 0x2b, 0x35, 0x6c, 0xd4, 0x17, 0x97, 0xfb, 0xdd, 0x6a, 0xd4, 0x77, 0xff,
	0x9d, 0xe9, 0x53, 0xfa, 0x7d, 0xb0, 0x59, 0x5f, 0xa9, 0xe1, 0x5d, 0x34, 0x5f, 0xaf, 0x8f, 0x1d,
	0x6a, 0xb2, 0x33, 0xe2, 0xeb, 0x7c, 0x1a, 0xce, 0xd4, 0x88, 0xeb, 0x26, 0x51, 0x76, 0x64, 0x7c,
	0x03, 0x5d, 0x69, 0x90, 0x26, 0xb7, 0xfa, 0x10, 0x6f, 0x35, 0x5b, 0xa7, 0x4b, 0xea, 0xd5, 0xa8,
	0xaa, 0xd5, 0x19, 0xe6, 0xad, 0xd6, 0x1b, 0x55, 0xb5, 0x3a, 0xc3, 0x67, 0xab, 0x92, 0x5b, 0x75,
	0x9b, 0x55, 0x49, 0xbd, 0x1a, 0x55, 0xb5, 0x87, 0xed, 0xbc, 0x55, 0xaf, 0x51, 0x55, 0x7b, 0xd8,
	0x7e, 0xb6, 0x2a, 0xb9, 0x55, 0xbf, 0x59, 0x95, 0xd4, 0xab, 0xd9, 0xab, 0xe1, 0x5a, 0xde, 0xea,
	0x76, 0xb3, 0x57, 0xc3, 0xb5, 0x77, 0xe0, 0x95, 0xd4, 0xea, 0xc3, 0xc7, 0x78, 0x55, 0xf4, 0xea,
	0xa2, 0xd9, 0x7a, 0x55, 0x56, 0x14, 0x8a, 0x97, 0xc4, 0x9d, 0xc6, 0x3d, 0xb6, 0x1f, 0x85, 0xfc,
	0x35, 0xd1, 0x47, 0x97, 0x1b, 0xf4, 0xe4, 0x4d, 0xee, 0x36, 0x6f, 0xb2, 0x59, 0x97, 0x0d, 0x74,
	0xb5, 0xe1, 0xac, 0xb6, 0x8f, 0x23, 0x92, 0x6f, 0xd7, 0xf7, 0x78, 0xa7, 0xba, 0x05, 0xb8, 0xcd,
	0xb8, 0x6c, 0xcb, 0x7e, 0x0b, 0x5d, 0x6b, 0x3a, 0xba, 0x95, 0xda, 0xbd, 0xc1, 0xdb, 0xd5, 0xae,
	0xbf, 0x52, 0xbf, 0x36, 0x3a, 0x2f, 0xa9, 0xa3, 0xa1, 0x97, 0x7f, 0xde, 0xbe, 0xc9, 0x3b, 0x9c,
	0xc9, 0x05, 0xed, 0x84, 0x5e, 0xf6, 0x95, 0xdb, 0x41, 0x17, 0x64, 0x11, 0x72, 0xd5, 0x86, 0x38,
	0x99, 0x14, 0xe3, 0x4a, 0x65, 0xca, 0x2b, 0x3f, 0x7d, 0xd1, 0x64, 0x95, 0x9b, 0xea, 0x2b, 0x5f,
	0xe4, 0xb3, 0x62, 0xf5, 0x95, 0xaf, 0x54, 0xbf, 0x55, 0x79, 0xe5, 0x97, 0xcb, 0x2f, 0xa2, 0x51,
	0x3b, 0x8c, 0x8c, 0xd8, 0xf1, 0x08, 0x6c, 0xcf, 0x8d, 0x2c, 0x3c, 0xbf, 0x73, 0xc2, 0x0e, 0xa3,
	0xfb, 0x8e, 0x47, 0xd8, 0xf1, 0x87, 0xa5, 0x5c, 0x1c, 0x3b, 0x71, 0x62, 0x11, 0xf8, 0x88, 0x38,
	0xfe, 0xd8, 0x61, 0xb4, 0x91, 0x86, 0xd8, 0x91, 0x91, 0x23, 0x81, 0x6f, 0x0b, 0x66, 0x47, 0x9c,
	0xde, 0x19, 0x93, 0xc5, 0xd8, 0xa1, 0x98, 0x41, 0xe2, 0x84, 0xb6, 0x2b, 0x0e, 0xc5, 0x76, 0x18,
	0x89, 0x53, 0x59, 0x3a, 0x08, 0x76, 0xd3, 0x41, 0xee, 0xe7, 0x83, 0xac, 0xa7, 0x21, 0xed, 0x32,
	0x62, 0x7f, 0x1a, 0x03, 0x82, 0xa9, 0xe3, 0xdb, 0xf0, 0x51, 0x71, 0x2d, 0x60, 0x87, 0x51, 0x57,
	0x44, 0xd8, 0x00, 0x2e, 0xb1, 0xd2, 0xaf, 0xdd, 0x07, 0xfc, 0xe8, 0x38, 0xea, 0x12, 0x4b, 0x7c,
	0xed, 0x2e, 0xa0, 0x29, 0x2f, 0x0c, 0x63, 0x43, 0xbe, 0x59, 0xf8, 0x98, 0x38, 0x79, 0xb1, 0xf8,
	0x7a, 0x71, 0xbb, 0x70, 0x1d, 0x4d, 0x72, 0x72, 0x7d, 0x51, 0x7c, 0xc5, 0x38, 0x3e, 0x3c, 0x14,
	0x8f, 0xc3, 0xc1, 0x45, 0xb6, 0x84, 0xee, 0xb1, 0x6f, 0xf5, 0xa9, 0x12, 0x16, 0x24, 0x31, 0x3c,
	0x12, 0x67, 0xbe, 0x82, 0xdb, 0x4a, 0x62, 0x76, 0x36, 0xcc, 0xc0, 0x6c, 0xf6, 0x3d, 0x96, 0xb9,
	0x6c, 0xaa, 0xcd, 0xa1, 0xf1, 0x8c, 0xe3, 0x6b, 0xe7, 0xe3, 0xe2, 0x01, 0x05, 0xc4, 0x97, 0x4a,
	0xae, 0xac, 0x95, 0x2b, 0xfb, 0x84, 0xa4, 0xac, 0xa5, 0x2a, 0x6b, 0x15, 0xca, 0x3e, 0x29, 0x8d,
	0xd8, 0xaa, 0x28, 0x6b, 0xe5, 0xca, 0x3e, 0x25, 0x73, 0x15, 0x65, 0x2d, 0xa1, 0xcc, 0x90, 0x94,
	0xb5, 0x4a, 0xca, 0xba, 0x85, 0x67, 0x9f, 0x2e, 0x94, 0x75, 0x55, 0xcf, 0xba, 0x92, 0x67, 0xb8,
	0x18, 0xb1, 0x5b, 0xf1, 0xac, 0x5b, 0x78, 0x36, 0x90, 0x39, 0x55, 0x59, 0x37, 0xf5, 0xcc, 0x2c,
	0x94, 0x75, 0xcb, 0x9e, 0x75, 0x0b, 0xcf, 0x2c, 0x49, 0x99, 0xea, 0x59, 0x57, 0xf2, 0x8c, 0x48,
	0x23, 0x56, 0x3c, 0xeb, 0x16, 0x9e, 0xed, 0xc9, 0x5c, 0x45, 0x59, 0xea, 0x99, 0x2d, 0x29, 0x2b,
	0x7b, 0xd6, 0x2b, 0x3c, 0xdb, 0x2f, 0x94, 0xf5, 0x54, 0xcf, 0x7a, 0x92, 0x67, 0x4e, 0x31, 0x62,
	0xaf, 0xe2, 0x59, 0xaf, 0xf0, 0xec, 0x33, 0x32, 0xa7, 0x2a, 0xeb, 0xa5, 0x9e, 0x3d, 0x29, 0x94,
	0xf5, 0xca, 0x9e, 0xf5, 0x0a, 0xcf, 0x5c, 0x49, 0x99, 0xea, 0x59, 0x4f, 0xf2, 0xcc, 0x93, 0x46,
	0xac, 0x78, 0xd6, 0x2b, 0x3c, 0xf3, 0x65, 0xae, 0xa2, 0x2c, 0xf5, 0x2c, 0x90, 0x94, 0x95, 0x3d,
	0xeb, 0x17, 0x9e, 0x85, 0x85, 0xb2, 0xbe, 0xea, 0x59, 0x5f, 0xf2, 0xec, 0xb3, 0xc5, 0x88, 0xfd,
	0x8a, 0x67, 0xfd, 0xc2, 0x33, 0x2a, 0x73, 0xaa, 0xb2, 0x7e, 0xea, 0x59, 0x54, 0x28, 0xeb, 0x97,
	0x3d, 0xeb, 0x17, 0x9e, 0xc5, 0x92, 0x32, 0xd5, 0xb3, 0xbe, 0xe4, 0x59, 0x22, 0x8d, 0x58, 0xf1,
	0xac, 0x5f, 0x78, 0x36, 0x94, 0xb9, 0x8a, 0xb2, 0xd4, 0xb3, 0x03, 0x49, 0x99, 0xf0, 0x6c, 0x16,
	0x8d, 0xf1, 0x0b, 0x4c, 0x3e, 0x5e, 0x0b, 0x0e, 0x39, 0xc0, 0x6f, 0x30, 0xd9, 0x58, 0xad, 0x72,
	0x5e, 0x87, 0xa3, 0x72, 0x5e, 0x2f, 0xe7, 0xdb, 0xf0, 0xb4, 0x9c, 0x6f, 0x97, 0xf3, 0x4b, 0xf0,
	0xb9, 0x72, 0x7e, 0xa9, 0x9c, 0xef, 0xc0, 0xe7, 0xcb, 0xf9, 0x4e, 0x39, 0xbf, 0x0c, 0x5f, 0x28,
	0xe7, 0x97, 0xcb, 0xf9, 0x15, 0xf8, 0x62, 0x39, 0xbf, 0x52, 0xce, 0xaf, 0xc2, 0x97, 0xca, 0xf9,
	0x55, 0xf6, 0xde, 0x28, 0xf2, 0x6b, 0xf0, 0xe5, 0x91, 0x32, 0xb0, 0xc6, 0xaf, 0x70, 0x0b, 0x83,
	0x16, 0xe1, 0x2b, 0x82, 0x40, 0xb9, 0x45, 0x8b, 0x0a, 0xd2, 0x82, 0xaf, 0xaa, 0x48, 0x4b, 0x41,
	0x74, 0xf8, 0x9a, 0x8a, 0xe8, 0x0a, 0xd2, 0x86, 0xaf, 0xab, 0x48, 0x5b, 0x41, 0x96, 0xe0, 0x1b,
	0x2a, 0xb2, 0xa4, 0x20, 0x1d, 0xf8, 0xa6, 0x8a, 0x74, 0x14, 0x64, 0x19, 0xbe, 0xa5, 0x22, 0xcb,
	0x0a, 0xb2, 0x02, 0xdf, 0x56, 0x91, 0x15, 0x05, 0x59, 0x85, 0xef, 0xa8, 0xc8, 0xaa, 0x82, 0xac,
	0xc1, 0x77, 0x55, 0x44, 0x71, 0x57, 0x5f, 0x84, 0xef, 0x29, 0x88, 0xae, 0xb8, 0xab, 0xb7, 0xe0,
	0xfb, 0x2a, 0xa2, 0xb8, 0xab, 0xeb, 0xf0, 0x03, 0x15, 0x51, 0xdc, 0xd5, 0xdb, 0xf0, 0x43, 0x15,
	0x51, 0xdc, 0xd5, 0x97, 0xe0, 0x47, 0x2a, 0xa2, 0xb8, 0xab, 0x77, 0xe0, 0xc7, 0x2a, 0xa2, 0xb8,
	0xab, 0x2f, 0xc3, 0x4f, 0x54, 0x44, 0x71, 0x57, 0x5f, 0x81, 0x9f, 0xaa, 0x88, 0xe2, 0xae, 0xbe,
	0x0a, 0x3f, 0x53, 0x11, 0xc5, 0x5d, 0x7d, 0x0d, 0x7e, 0xae, 0x22, 0x8a, 0xbb, 0xed, 0x45, 0xf8,
	0x85, 0x82, 0xb4, 0x15, 0x77, 0xdb, 0x2d, 0xf8, 0xa5, 0x8a, 0xb4, 0xd8, 0xf9, 0xad, 0x40, 0x3c,
	0xc7, 0x87, 0x5f, 0x8d, 0xa4, 0xff, 0xc6, 0x48, 0x99, 0x4d, 0xc7, 0x57, 0x20, 0x7c, 0x08, 0xbf,
	0x56, 0x21, 0x7c, 0x58, 0x86, 0xf0, 0xd0, 0x86, 0xdf, 0x28, 0xd0, 0xfa, 0xd0, 0xe6, 0xff, 0x79,
	0xc8, 0x21, 0x7e, 0x91, 0xf2, 0x5b, 0x41, 0x8d, 0x67, 0x14, 0xbf, 0x3b, 0xb9, 0x8a, 0x26, 0xf8,
	0x39, 0xcd, 0x88, 0xf0, 0x90, 0xdf, 0xf3, 0xff, 0x6e, 0x24, 0xbd, 0xe8, 0x67, 0xd1, 0x5d, 0x3c,
	0x24, 0x5b, 0xbe, 0x36, 0x87, 0xc6, 0x28, 0xc1, 0x74, 0xe8, 0x90, 0x03, 0x86, 0xfc, 0x5e, 0x20,
	0x28, 0x8b, 0x09, 0xc2, 0x73, 0xcc, 0xfc, 0x4e, 0xf1, 0x0f, 0x29, 0xe1, 0x39, 0x66, 0x76, 0x91,
	0x78, 0x09, 0x8d, 0x3a, 0x5e, 0x22, 0xf6, 0xcf, 0x3f, 0x8a, 0xf4, 0x09, 0xc7, 0x4b, 0xf8, 0xee,
	0x39, 0x8f, 0xc6, 0x59, 0xce, 0xc3, 0xb6, 0x4f, 0x62, 0xe3, 0x10, 0xfe, 0x94, 0x96, 0x3b, 0x5e,
	0xb2, 0xc9, 0x63, 0x0f, 0x15, 0xe4, 0x08, 0xfe, 0xac, 0x22, 0x8f, 0x14, 0xe4, 0x29, 0xfc, 0x45,
	0x45, 0x1e, 0x6b, 0x33, 0x88, 0xfd, 0x65, 0xd8, 0x47, 0x34, 0x30, 0x0e, 0xe1, 0xaf, 0x02, 0x60,
	0xba, 0xee, 0x1c, 0xd1, 0xe0, 0x61, 0x29, 0x7d, 0x04, 0x7f, 0x2b, 0xa7, 0x1f, 0x95, 0xd2, 0x4f,
	0xe1, 0xef, 0xe5, 0xf4, 0x63, 0xb6, 0x07, 0xb2, 0x34, 0x36, 0x4d, 0xe2, 0x1a, 0x87, 0xf0, 0x0f,
	0x91, 0x3f, 0xe9, 0x78, 0xc9, 0x3a, 0x0b, 0x3d, 0x2c, 0x03, 0x47, 0xf0, 0x4f, 0x05, 0x78, 0x54,
	0x06, 0x9e, 0xc2, 0xbf, 0x14, 0xe0, 0xb1, 0x76, 0x0f, 0xcd, 0x0f, 0xbc, 0xc8, 0x38, 0xfe, 0xe2,
	0xee, 0xdf, 0xe2, 0x77, 0x9e, 0x19, 0x78, 0xd1, 0x46, 0xf3, 0xe5, 0xdd, 0x9b, 0xe8, 0x0a, 0x6b,
	0xf5, 0x8c, 0x0b, 0xbc, 0xff, 0x88, 0x5e, 0xb3, 0x03, 0x2f, 0xda, 0x39, 0xe6, 0x12, 0xef, 0x0e,
	0x9a, 0x63, 0xcd, 0x1a, 0x2f, 0xf2, 0xa2, 0xc4, 0x83, 0xff, 0x8a, 0x56, 0x2f, 0x0e, 0xbc, 0xa8,
	0xbe, 0xcb, 0x6e, 0xe2, 0x69, 0x37, 0xd1, 0x64, 0x88, 0xcd, 0x27, 0x24, 0x8e, 0x8c, 0x90, 0x4d,
	0x4a, 0x62, 0xc2, 0xff, 0x44, 0xdd, 0x44, 0x1a, 0xdf, 0x26, 0x74, 0x97, 0x98, 0x6f, 0x07, 0x00,
	0x00, 0xff, 0xff, 0xbc, 0x95, 0x87, 0x64, 0x53, 0x1d, 0x00, 0x00,
}
