version: '3'
services:
  telemetry:
    build:
      context: .
    links:
      # Link to influx so we can save to influx
      - influxdb
      - jaeger
    volumes:
      # Mount for csvs and blog files
      - ~/csvs/:/csvs/   # CSVs saved to ~/csvs on host
      - ~/blogs/:/blogs/ # Blogs saved to ~/blogs on host
    ports:
      # GRPC service on port 9090
      - "9090:9090"
      # UDP packets on port 33333 from car
      - "33333:33333/udp"
    depends_on:
      - influxdb
      - jaeger

  # ============================== influx ==============================
  chronograf:
    # Full tag list: https://hub.docker.com/r/library/chronograf/tags/
    image: quay.io/influxdb/chronograf:1.4.1.3
    volumes:
      # Mount for chronograf database
      - ./sandbox/chronograf/data/:/var/lib/chronograf/
    links:
      # Chronograf requires network access to InfluxDB and Kapacitor
      - influxdb
      - kapacitor
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - kapacitor
      - influxdb
      - telegraf
  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    image: telegraf:1.5.2
    environment:
      HOSTNAME: "telegraf-getting-started"
    # Telegraf requires network access to InfluxDB
    links: 
      - influxdb
    volumes:
      # Mount for telegraf configuration
      - ./sandbox/telegraf/:/etc/telegraf/
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    image: influxdb:1.4.3
    volumes:
      # Mount for influxdb data directory
      - ./sandbox/influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./sandbox/influxdb/config/:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
  kapacitor:
    # Full tag list: https://hub.docker.com/r/library/kapacitor/tags/
    image: kapacitor:1.4.0
    volumes:
      # Mount for kapacitor data directory
      - ./sandbox/kapacitor/data/:/var/lib/kapacitor
      # Mount for kapacitor configuration
      - ./sandbox/kapacitor/config/:/etc/kapacitor/
    # Kapacitor requires network access to Influxdb
    links:
      - influxdb
    ports:
      # The API for Kapacitor is served on port 9092
      - "9092:9092"
  documentation:
    build:
      context: ./sandbox/documentation
    ports: 
      - "3010:3000"
  # ========================== jaegertracing ==========================
  # Docs here: http://jaeger.readthedocs.io/en/latest/getting_started/
  jaeger: 
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp" # agent - UDP - Zipkin Thrift
      - "6831:6831/udp" # agent - UDP Jaeger compact thrift
      - "6832:6832/udp" # agent - UDP Jaeger binary thrift
      - "5778:5778"     # agent - HTTP - serve configs
      - "16686:16686"   # query - HTTP - serve frontend
      - "14268:14268"   # collector - HTTP - accept jaeger.thrift from clients
      - "9411:9411"     # collector - HTTP - Zipkin endpoint
      
