ignored = ["github.com/sscp/telemetry/sandbox"]
required = ["github.com/russross/blackfriday"]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/jackbeasley/structs"
  branch = "master"
  source = "github.com/jackbeasley/structs"

[[constraint]]
  branch = "master"
  name = "github.com/russross/blackfriday"
